<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="renderer" content="webkit">
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">
	
	<meta name="viewport" content="width=device-width,height=device-height,maximum-scale=2.0,initial-scale=1.0">
	<meta name="apple-mobile-web-app-title" content="标题">
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="MobileOptimized" content="320"/>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php isset($seot) || $seot = isset($this->layout['seot']) ? $this->layout['seot'] : $layout["lang"]["TITLE_WORD"]; ?>
	<title>
		<?php  echo  $seot?:$layout["lang"]["TITLE_WORD"]?>
	</title>
	<meta name="keywords" content="<?php  echo isset($this->layout['seok'])?$this->layout['seok']:$lang['KEY_WORDS']?>" />
	<meta name="description" content="<?php echo isset($this->layout['seod'])?$this->layout['seod']:$lang['DESCRIPTION']?>" />
	<meta content="telephone=no,email=no" name="format-detection">
	<link rel="shortcut icon" href="/lendenex.jpg" />
	<?php $hasLibs = file_exists(PATH_TPL.'/../../../public/libs.json'); ?>
	<?php if($hasLibs) { $libs = json_decode(file_get_contents(PATH_TPL.'/../../../public/libs.json'), true);} ?>
	<?php if ($hasLibs && $libs['libs']['css']) { ?>
	<link rel="stylesheet" href="<?php echo "/libs".'/'.$libs['libs']['css'] ?>" />
	<?php }?>
	<?php $statics = json_decode(file_get_contents(PATH_TPL.'/../../../public/version.json'), true); ?>
	<?php foreach ($statics[$layout['controller'].'.'.$layout['action']]['css'] as $v) {
    if ($v) echo "<link rel='stylesheet' href='$v' />";
  } ?>
</head>
<body class="default_bg default_f" id="body_all">
	<span id="LANG" style="display:none;"><?php echo LANG ?></span>
	<div flex="main:justify cross:center" class="nav_contain" id="navApp">
		<div class="nav_left" flex="dir:left cross:center">
			<a class="main_link" href="/">
				<img src="/svg/lendenexLogo.svg">
			</a>
			<ul flex="dir:left" class="nav_left_sec">
				<?php if ($layout['controller'] != 'trade'){ ?>
					<li class="index rel-dom act-nav-list"><a href="/" class="link"><?php echo $layout['lang']["HOME"]; ?></a></li>
					<li ><a class="link gray700_f" href="/trade"><?php echo $layout['lang']["TRADE_CENTER"]; ?></a></li>
					<?php $rewardurl = Yaf_Registry::get("config")->header->rewardurl; if ($rewardurl) { ?>
						<li class="rel-dom act-nav-list">
							<a class="link gray700_f" href="<?php echo $rewardurl;?>"><?php echo $layout['lang']["ACTIVITY_NEWS"]; ?></a>
						</li>
					<?php } ?>
					<li class="rel-dom act-nav-list">
						<a class="link gray700_f" 
							<?php  if(isset($_SESSION['user'])) {echo 'href="/user/index"';} else{echo "@click.stop='login'";}?>><?php echo $GLOBALS['MSG']['FINANCIAL_CENTER'];?></a>
					</li>
					
				<?php } ?>
			</ul>
		</div>
		<ul flex="dir:left" class="nav_right gray700_f">
			<!-- // 1. nologin -->
			<?php if (!isset($_SESSION['user'])){ ?>
				<li flex="main:justify cross:center">
					<button class="login_btn" @click.stop="login"><?php echo $layout['lang']["LOGIN"]; ?></button>
					<button class="register_btn " @click.stop="register"><?php echo $layout['lang']["REGISTER"]; ?></button>
				</li>
			<?php } ?>
			<!-- //2. hadlogin //userMainu = !userMainu  -->
			<?php if (isset($_SESSION['user'])) { ?>
				<li :class="['relative_dom', 'user_part', {now_nav: userMainu}]" @click.stop="changeTab('userMainu')" flex="cross:center">
					<!-- // personalcenter user_icon -->
					<span class="user_icon_person"></span>
					<a class="gray700_f relative_dom ctrl_icon margin_left_z">
						<?php 
						if($_SESSION['user']['mo']){echo substr($_SESSION['user']['mo'], 0, 3).'****'. substr($_SESSION['user']['mo'], 7, 4);}
						else{ $email_array = explode("@", $_SESSION['user']['email']);
							$not= substr_replace($email_array[0], '****', 3);
							$userInfo['email']= $not.'@'.$email_array[1];  echo $userInfo['email'];
						} ?>
						<i class="more-i"></i>
					</a>
					<!-- <div class="user_acc_mask" v-cloak> -->
					<transition mode="out-in" name="fadeOut">
					<ul class="user_account_contain" v-cloak v-if="userMainu">
						<li><a class="gray700_f account_list accout_a" href="/user"><?php echo $layout['lang']['MY_ACCOUNT']; ?></a></li>
						<li><a class="gray700_f logout_list accout_a" href="/user/logout"><?php echo $layout['lang']['LOGOUT']; ?></a></li>
					</ul>
					</transition>
					<!-- </div> -->
				</li>
			<?php } ?>
			<li :class="['relative_dom', 'more_tr', {now_nav: lang}]" @click.stop="changeTab('lang')" flex="cross:center">
				<?php $langImgVersion=1; ?>
				<img src="/flag/<?php echo LANG ?>.png?v=<?php echo $langImgVersion; ?>" alt="" class="nav_flag"/>
				<a class="gray700_f link ctrl_icon margin_left_z"></a>
				<!-- <div class="user_acc_mask" v-cloak> -->
				<transition mode="out-in" name="fadeOut">
					<!-- v-on:mouseout="lang = false" -->
					<div class="user_account_contain user_account_flag" v-cloak v-if="lang">
						<ul class="black500_f">
							<?php foreach ($layout['country'] as $key => $cou) { ?>
							<li>
								<a class="gray700_f flag_a <?php if(LANG=='<?php echo $key; ?>') { echo " hover_click"; } ?>"
									@click="changeLangs('<?php echo $key; ?>')">
									<img src="/flag/<?php echo $key; ?>.png?v=<?php echo $langImgVersion; ?>" alt="" class="nav_flag">
									<?php echo $cou; ?>
								</a>
							</li>
							<?php } ?>
						</ul>
					</div>
				</transition>
				<!-- </div> -->
			</li>
		</ul>
		<?php // reqToken ?>
		<span id="hahaha" style="display: none !important;">
			<?php echo $layout['reqToken'] ?></span>
		<input type="hidden" value="<?php echo Yaf_Registry::get("config")->push->host;?>" id="wsurl" />
	</div>

	<!-- <script>
		(function(a,h,c,b,f,g){a["UdeskApiObject"]=f;a[f]=a[f]||function(){(a[f].d=a[f].d||[]).push(arguments)};g=h.createElement(c);g.async=1;g.charset="utf-8";g.src=b;c=h.getElementsByTagName(c)[0];c.parentNode.insertBefore(g,c)})(window,document,"script","https://assets-cli.udesk.cn/im_client/js/udeskApi.js","ud");
		ud({
			"code": "2f6kec52",
			"link": "https://fwzs6.udesk.cn/im_client/?web_plugin_id=52422"
		});
		if(/\/?login/.test(window.location.href)){
			window.location.href="/signin/?aa=lo"
		}
	</script> -->
<style>
		li.hot {
			position: relative;
		}	
		li.hot::after {
				position: absolute;
				right: -21px;
				top: 18px;
				background: url(https://file.huobiasia.vip/global/image/icon_%20bubbling.c288a13.svg) no-repeat 50%;
				background-size: contain;
				content: '';
				padding: 9px 19px;
		}
</style>
