<!DOCTYPE html>

<html>
<haed>
    <mete charset="utf-8"/>
    <title>聊天室</title>

    <style>
        #result{overflow-y:scroll;width: 500px;height: 400px;border: 4px solid #ddd;background: #eee;padding: 0 10px;}
        #message{width: 500px;}
        p>span{border-radius: 5px;padding: 4px 6px}
        .mine{background: #0a0;color: #fff}
        .their{background: #fff;color:#000}
    </style>

<!--    <script src="http://pv.sohu.com/cityjson?ie=utf-8"></script>-->
<!--    <script type="text/javascript">-->
<!--        console.log(returnCitySN["cip"]+','+returnCitySN["cname"])-->
<!--    </script>-->
</haed>

<doby>

    <div id="result">
        <?php foreach ($msg as $v){
            if($v['secret']== $key['secret']){?>
                <p style="text-align:right"><span class="mine"><?php echo $v['msg'];?></span>: 我</p>
            <?php }else{?>
                <p><?php echo $key['cmo'];?>: <span class="their"><?php echo $v['msg'];?></span></p>
                <?php
            }
        }?>
    </div>
    <from>
<!--        <p>昵称: <input type="text" id="username"></p>-->
        <p><textarea cols="50" rows="3" id="message"></textarea></p>
        <p><button id="btn" type="button">发送</button></p>
        <input id="smo" value="<?php echo $key['smo'];?>" hidden/>
        <input id="cmo" value="<?php echo $key['cmo'];?>" hidden/>
        <input id="secret" value="<?php echo $key['secret'];?>" hidden/>
        <input id="client" value="<?php echo $key['client'];?>" hidden/>
    </from>

    <script>
        //使用webSocket对象连接
        var ws = new WebSocket('ws://192.168.1.111:9502');
        
        //绑定连接事件
        ws.onopen=function () {
            var data = {cmd:'chat.register',data:{secret:secret.value,client:client.value}}
            ws.send(JSON.stringify(data));//发送数据
            result.innerHTML+='<p>连接服务器成功...</p>';
            result.scrollTop=result.scrollHeight;
        }

        //绑定断开连接事件
        ws.onclose=function () {
            result.innerHTML+='<p>服务器已断开...</p>';
        }

        //发送信息
        btn.onclick=function () {
            var data = {cmd:'chat.send',data:{message:message.value,secret:secret.value,client:client.value}};//fromuserid:window.userid,username:username.value,
            ws.send( JSON.stringify(data));//发送数据
            result.innerHTML+='<p style="text-align:right"><span class="mine">'+message.value+'</span>: 我</p>';
            message.value = '';
            result.scrollTop=result.scrollHeight;
        }

        //接收消息
        ws.onmessage=function (res) {
            var data = JSON.parse(res.data);

            if(data.status==0){
                result.innerHTML+='<p>已打开新的窗口,请关闭当前窗口...</p>';
                return false;
            }
            result.innerHTML+='<p>'+cmo.value+': <span class="their">'+data.message+'</span></p>';
            result.scrollTop=result.scrollHeight;//获取盒子总高度作为滚动的高度，将最后的内容展示
        }
    </script>
</doby>
</html>


