<link href="/websiteoutcss/bootstarp.css" rel="stylesheet">
<?php  include PATH_TPL.'/tpl.header.phtml';?>
<div class="bg-content" id="c2c">

    <div style="margin:0 auto;max-width:1200px;width:100%">
        <div class="c2cmain">
            <!-- <p><?php echo $repeat_del;?></p> -->
            <input type="hidden" value="<?php echo $repeat_del;?>" id="token" />

            <div class="header c2cTitle">
                <h4 class="c2c_trans">
                    <?php echo $GLOBALS['MSG']['C2C_TRADING'];?>
                </h4>
                <div class="fR">
                    <a href="/user/bank" style="padding: 17px;color: rgb(255, 189, 9);text-decoration: none;" class="fa fa-credit-card fa-fw">
                        <?php echo $GLOBALS['MSG']['COLLECT_PAY_MANAGE'];?>
                    </a>
                    <?php echo $GLOBALS['MSG']['AVAILABEL_BALANCE'];?>：<span style="color:#ffbd09;padding-right: 34px" v-text="cnyxover"></span>
                    <?php echo $GLOBALS['MSG']['FREEZE_BLANCE'];?>：<span style="color:#ffbd09" v-text="cnyxlock"></span>
                </div>
            </div>
            <div class="finance-rd" style="width: 100%;margin-left: 0px;background: white;padding: 32px 20px 30px;">
                <!-- buy -->
                <div class="row">
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-sm-6 col-xs-12 buy">
                                <h3 class="b-title" style="margin-bottom: 12px">
                                    <?php echo $GLOBALS['MSG']['HK_BUY_IN'];?> CNYX</h3>
                                <div id="buyDefaultForm">
                                    <div class="form-group has-feedback form-subline">
                                        <label for="buyUnitPrice" class="control-label">
                                <span class="buyDefaultLabel"><?php echo $GLOBALS['MSG']['BUY_PRICE'];?></span> (￥)
                                        </label>
                                        <div class="input-group">
                                            <input type="hidden" value="1.0000">
                                            <input type="text" id="buyUnitPrice" name="buyUnitPrice" disabled="disabled" 
                                            readonly="readonly" value="1.00" class="form-control form-second" style="color:#0fbb90"/>
                                        </div>
                                    </div>
                                    <div class="form-group has-feedback form-subline">
                                        <label for="buyNumber" class="control-label"><?php echo $GLOBALS['MSG']['BUY_NUM'];?> (CNYX)</label>
                                        <div class="input-group">
                                            <input type="text" name="buyNumber" class="form-control form-second" v-model="Purchase" autocomplete="off" 
                                            oninput = "value=value.replace(/[^\d||\.]/g,'')"/>
                                        </div>
                                    </div>
                                    <div id="buyfinish" style="color: darkgray;">
                                        <?php echo $GLOBALS['MSG']['NEED'];?> <span style="color:#ffbd09" v-text="Purchase"></span> (￥)
                                    </div>
                                    <div class="form-group" v-cloak>
                                        <!-- 判断有没有登陆 -->
                                        <button v-if="parseInt(<?php echo isset($_SESSION['user'])?>)" id="buyBtn" class="btn btn-yellow btn-block ft16"
                                         @click="buyimmediately" ><?php echo $GLOBALS['MSG']['BUY_IMMEDIATE'];?></button>
                                         <!-- 没有登陆,去登陆 -->
                                        <button v-else @click="login" class="btn btn-yellow btn-block ft16"><?php echo $GLOBALS['MSG']['LOGIN'];?></button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-xs-12 sell">
                                <h3 class="b-title" style="margin-bottom: 12px"><?php echo $GLOBALS['MSG']['SELL'];?> CNYX</h3>
                                <input type="hidden" id="urgent" value="<?php if($urgent['is_lock']==1){echo '2';}else{ echo '1'; }?>">
                                <div class="Urgent">
                                    ( <label> <input class="radio_input" type="radio" name="sltype" value="1" v-model="Urgent"><?php echo $GLOBALS['MSG']['ORDINARY'];?></label>
                                    <?php if($urgent['is_lock']==1){?>
                                    <label><input class="radio_input" type="radio" name="sltype" value="2" v-model="Urgent"><?php echo $GLOBALS['MSG']['URGENT'];?> </label>
                                    <?php }
                                        ?> )
                                </div>

                                <div id="sellDefaultForm">
                                    <div class="form-group has-feedback form-subline">
                                        <label for="buyUnitPrice" class="control-label">
                                    <span class="sellDefaultLabel"><?php echo $GLOBALS['MSG']['SELL_PRICE'];?></span> (￥) 
                                </label>
                                        <div class="input-group">
                                            <input type="hidden" value="1.00" disabled>
                                            <input type="text" id="sellUnitPrice" name="sellUnitPrice" readonly="readonly" disabled="disabled" value="1.00" 
                                            class="form-control form-second" style="color:#ee2222"></div>
                                    </div>
                                    <div class="form-group has-feedback form-subline">
                                        <div class="input-group">
                                            <input type="text" placeholder="<?php echo $GLOBALS['MSG']['SELL_NUM'];?> (CNYX)" style="width:49%;text-align: left;"
                                            class="form-control form-second" v-model="sellout" autocomplete="off"
                                            oninput = "value=value.replace(/[^\d||\.]/g,'')"  ><input 
                                            oninput = "value=value.replace(/[^\d||\.]/g,'')"
                                            type="text" placeholder="最小賣出数量" style="width:49%;margin-left:2%;text-align: left;"   
                                            class="form-control form-second" v-model="sellMin" autocomplete="off">
                                        </div>
                                    </div>
                                    <div id="sellfinish" style="color: darkgray;">
                                        <?php echo $GLOBALS['MSG']['CAN_GAIN'];?> <span style="color:rgb(0, 153, 153)" v-text="sellout"></span>(￥)
                                    </div>
                                    <div class="form-group" v-cloak>
                                        <button v-if="parseInt(<?php echo isset($_SESSION['user'])?>)" id="sellBtn"  class="btn btn-second btn-block ft16" @click="sellimmediately"><?php echo $GLOBALS['MSG']['SELL_IMMEDIATE'];?></button>
                                        <button v-else  @click="login" class="btn btn-second btn-block ft16">
                                        <?php echo $GLOBALS['MSG']['LOGIN'];?></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row h5hide">
                    <div class="col-xs-6">
                        <div class="exchangetlist" id="usdtcnybuylist">
                            <div class="shd">
                                <span class="line_h"><?php echo $GLOBALS['MSG']['MERCHANT_BUY_ORDER'];?></span>
                                <b class="line_h"><?php echo $GLOBALS['MSG']['TRADABLE_QUANTITY'];?></b>
                                <span class="typeshow"><?php echo $GLOBALS['MSG']['PAY_TYPE'];?></span>
                                <a style="color:#0fbb90"><?php echo $GLOBALS['MSG']['URGENT'];?></a>
                                <a style="color:#0fbb90">
                                    <?php echo $GLOBALS['MSG']['OPERATE'];?>
                                </a>
                            </div>
                            <div class="bd">
                                <div class="tempWrap">
                                <ul v-cloak>
                                        <li v-for="(itime,key) in selllist">
                                            <span v-text="itime.moble.slice(0,4) +'***'+ itime.moble.slice(-4) "></span>
                                            <b >{{parseInt(itime.min) > parseInt(itime.deal)?parseInt(itime.deal):parseInt(itime.min)}} ~{{parseInt(itime.deal)}} </b>
                                            <!-- 支付方式 -->
                                            <span class="typeshow">
                                                <strong v-if="itime.bank==1"><?php echo $GLOBALS['MSG']['ONLINE_BANK'];?>
                                                </strong><strong v-if="itime.wechat==2"><?php echo $GLOBALS['MSG']['WECHAT'];?>
                                                </strong><strong v-if="itime.alipay==3"><?php echo $GLOBALS['MSG']['ALIPAY'];?></strong >
                                           </span>
                                           <a style="color:rgb(255, 189, 9)" v-text="itime.selltype=='2'?'<?php echo $GLOBALS['MSG']['URGENT'];?>':'<?php echo $GLOBALS['MSG']['ORDINARY'];?>'"></a>
                                            <a >
                                                <button v-if="parseInt(<?php echo isset($_SESSION['user'])?>)"  class="btn btn-yellow" style="height:30px;line-height:18px" 
                                                @click="buySell(1,itime.id,itime.min,itime.deal)"><?php echo $GLOBALS['MSG']['BUY'];?></button>
                                                <button  v-else  @click="login" class="btn btn-yellow " style="height:30px;line-height:18px" ><?php echo $GLOBALS['MSG']['LOGIN_NO'];?></button>
                                            </a>
                                        </li>
                                    </ul>
                                   
                                </div>
                            </div>

                        </div>
                    </div>
                    <!-- sell-->
                    <div class="col-xs-6">
                        <div class="exchangetlist" id="usdtcnyselllist">
                            <div class="shd">
                                <span ><?php echo $GLOBALS['MSG']['MERCHANT_SELL_ORDER'];?></span>
                                <b ><?php echo $GLOBALS['MSG']['TRADABLE_QUANTITY'];?></b>
                                <span class="typeshow"><?php echo $GLOBALS['MSG']['PAY_TYPE'];?></span>
                                <a style="color:#ee2222">
                                    <?php echo $GLOBALS['MSG']['OPERATE'];?>
                                </a>
                            </div>
                            <div class="bd">
                                <div class="tempWrap" >
                                    <ul v-cloak>
                                        <li v-for="(itime,key) in buylist">
                                            <span  v-text="itime.moble.slice(0,4) +'***'+ itime.moble.slice(-4) "></span>
                                            <b  v-text="itime.deal"></b>
                                            <!-- 支付方式 -->
                                            <span class="typeshow">
                                                <strong v-if="itime.bank==1"><?php echo $GLOBALS['MSG']['ONLINE_BANK'];?>
                                                </strong><strong v-if="itime.wechat==2"><?php echo $GLOBALS['MSG']['WECHAT'];?>
                                                </strong><strong v-if="itime.alipay==3"><?php echo $GLOBALS['MSG']['ALIPAY'];?></strong >
                                           </span>
                                            <a>
                                                <button v-if="parseInt(<?php echo isset($_SESSION['user'])?>)" class="btn btn-second" style="height:30px;line-height:18px"  
                                                @click="buySell(2,itime.id,itime.deal)" ><?php echo $GLOBALS['MSG']['SELL'];?></button>
                                                <button v-else @click="login" class="btn btn-second" style="height:30px;line-height:18px" ><?php echo $GLOBALS['MSG']['LOGIN_NO'];?></button>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="usdtnote">
                    <div class="notecont">
                        <p style="color:#ffbd09">1.
                            <?php echo $GLOBALS['MSG']['ORDER_ARRIVE'];?>；</p>
                        <p style="color:#ffbd09">2.
                            <?php echo $GLOBALS['MSG']['WITHIN_TIME_LIMIT'];?>；</p>
                        <p>3.
                            <?php echo $GLOBALS['MSG']['CONFIRM_GAIN_MONEY'];?>；</p>
                        <p>4.
                        <?php echo $GLOBALS['MSG']['TOP_UP_SINGLE'];?>；</p>
                        <p>5.
                            <?php echo $GLOBALS['MSG']['MIN_AMOUNT'];?>；</p>
                        <p>6.
                            <?php echo $GLOBALS['MSG']['RATE'];?>;</p>
                        <p>7.
                            <?php echo $GLOBALS['MSG']['CONFIRM_RECEIPT'];?>；</p>
                        <p>8.
                            <?php echo $GLOBALS['MSG']['GOOD_EVIDENCE'];?>。</p>
                    </div>
                </div>
                <div class="bk-pageTit" id="exchangeRecord">
                    <h4 class="pull-left">
                        <i class="bk-ico assetRecord"></i>
                        <?php echo $GLOBALS['MSG']['EXCHANGE_RECORD'];?>
                    </h4>
                    <div class="clearfix"></div>
                    <div class="table-responsive">
                        <table id="billDetail" class="table table-striped table-bordered table-hover" v-cloak>
                            <thead>
                                <tr>
                                    <th width="13%">
                                        <?php echo $GLOBALS['MSG']['TIME'];?>
                                    </th>
                                    <th width="5%" style="text-align:left;">
                                        <?php echo $GLOBALS['MSG']['TRANSACTION_TYPE'];?>
                                    </th>
                                    <th width="6%" style="text-align:left;">
                                        <?php echo $GLOBALS['MSG']['RUN_NUM'];?>
                                    </th>
                                    <th width="9%" style="text-align:left;">
                                        <?php echo $GLOBALS['MSG']['ALL_NUM'];?>
                                    </th>
                                    <th width="9%" style="text-align:left;">
                                        <?php echo $GLOBALS['MSG']['MATCH_NUM'];?>
                                    </th>
                                    <th width="9%" style="text-align:left;">
                                        <?php echo $GLOBALS['MSG']['ORDER_PRICE'];?>
                                    </th>
                                    <th width="5.8%" style="text-align:left;">
                                        <?php echo $GLOBALS['MSG']['UNIT_PRICE'];?>(￥)</th>
                                    <th width="9%" style="text-align:left;">
                                        <?php echo $GLOBALS['MSG']['BALANCE'];?>(￥)</th>
                                    <th width="5%">
                                        <?php echo $GLOBALS['MSG']['STATUS'];?>
                                    </th>
                                    <th width="15%">
                                        <?php echo $GLOBALS['MSG']['OPERATE'];?>
                                    </th>
                                    <th width="5%">
                                        <?php echo $GLOBALS['MSG']['IF_URGENT'];?>
                                    </th>
                                    <th width="13%">
                                        <?php echo $GLOBALS['MSG']['PAY_TYPE'];?>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="(item,key) in list">

                                    <td v-text="item.addtime"></td>
                                    <td>
                                        <span style="color:ffbd09" v-if="item.type==1" v-cloak><?php echo $GLOBALS['MSG']['BUY_IN'];?></span>
                                        <span style="color:#5cb85c" v-else-if="item.type==2" v-cloak><?php echo $GLOBALS['MSG']['SELL'];?></span>
                                    </td>
                                    <td v-text="item.tradeno"></td>
                                    <td v-text="item.price"></td>
                                    <td v-text="item.num"></td>
                                    <td v-text="item.orderprice"></td>
                                    <td v-text="1"></td>
                                    <td v-text="item.deal"></td>
                                    <input type="hidden" v-text="token">
                                    <td style="text-aligin:center">   
                                        <!-- 倒计时 -->
                                        <!-- {{item.status}}
                                        <br>deal_time={{ item.deal_time}}=={{item.itimes}}
                                        <br>pay_time={{ item.pay_time}}=={{item.itime}}<br/> -->
                                        
                                        <p v-if="item.status == 2 && item.pay_time>0 && item.itime" v-text="item.itime"></p>
                                        <p v-if="item.status == 0 && item.deal_time>0 && item.itimes && item.type != 2" v-text="item.itimes"></p>
                                        <!-- 状态 -->
                                        <span class="status1" v-if="item.status==0 && item.deal_id==0" v-cloak><?php echo $GLOBALS['MSG']['NO_MATCH'];?></span>
                                        <span class="status2" v-else-if="item.status==1" v-cloak><?php echo $GLOBALS['MSG']['HAD_FINISH'];?></span>
                                        <span class="status3" v-else-if="item.status==2" v-cloak><?php echo $GLOBALS['MSG']['HAD_PAY'];?></span>
                                        <span class="status4" v-else-if="item.status==3" v-cloak> <?php echo $GLOBALS['MSG']['WITHDRAWN'];?></span>
                                        <span class="status5" v-else-if="item.status!=3 && item.status!=1 && item.id!=0 && item.status!=2" v-cloak><?php echo $GLOBALS['MSG']['HAD_MATCH'];?></span>
                                    </td>
                                    <td>
                                         <!--我已付款  -->
                                        <span class="btn btn-success" v-if="item.type==1 && item.deal_id>0&&(item.status!=3 && item.status!=2&& item.status!=1)" @click="paid(item.id,key)" 
                                        :style="{cursor:(!dubclick?'wait':'pointer')}" v-cloak><?php echo $GLOBALS['MSG']['I_HAD_PAY'];?></span>
                                         <!--撤单  -->
                                        <span class="btn btn-info" v-if="item.type==1 && item.status==0" :style="{cursor:(!dubclick?'wait':'pointer')}" @click="Revoke(item.id,key,item.type)"
                                         v-show="Revokes" v-cloak><?php echo $GLOBALS['MSG']['UNDO'];?></span>
                                         <!--确认收款按钮-->
                                        <span class="btn btn-success" v-if="item.type==2 && item.status==2 && item.deal_id" :style="{cursor:(!dubclick?'wait':'pointer')}"
                                         @click="Confirmreceipt(item.id,key)" v-cloak><?php echo $GLOBALS['MSG']['F_CONFIRM_RECEIPT'];?></span>
                                         <!--撤单  -->
                                        <span class="btn btn-info" v-else-if="item.type==2 &&item.status==0 && item.deal_id==0" :style="{cursor:(!dubclick?'wait':'pointer')}"
                                         @click="Revoke(item.id,key,item.type)" v-cloak><?php echo $GLOBALS['MSG']['UNDO'];?></span>
                                    </td>
                                    <td>
                                        <span v-if="item.selltype==1" v-cloak><?php echo $GLOBALS['MSG']['URGENT_NO'];?></span>
                                        <span v-else-if="item.selltype==2" v-cloak><?php echo $GLOBALS['MSG']['URGENT'];?></span>
                                    </td>
                                    <td>
                                        <span class="typeshow iconfont icon-WY" v-show="item.deal_id!=0 && item.yhk==1" @click="show(item.id,1)" v-cloak></span>
                                        <span class="typeshow iconfont icon-WX" v-show="item.deal_id!=0 && item.wx==2" @click="show(item.id,2)" v-cloak></span>
                                        <span class="typeshow iconfont icon-ZFB" v-show="item.deal_id!=0 && item.yfb==3" @click="show(item.id,3)" v-cloak></span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="tabsPages" :class="all > 1 ? 'page-list-contain':''">
                            <pages :all="all" v-on:get-tabs="getcoindata" 
                                :page-name="'<?php echo $GLOBALS['MSG']['PAGE'];?>'" 
                                :jump-to-title="'<?php echo $GLOBALS['MSG']['JUMP'];?>'"
                                :home-title="'<?php echo $GLOBALS['MSG']['NUMBER_HOME'];?>'"
                                :last-title="'<?php echo $GLOBALS['MSG']['NUMBER_FOOR'];?>'"
                                :currentpage="currentpage" @keydown="" v-if="all && all != 1">
                            </pages>
                        </div>
                        <input type="hidden" id="pageIndex" value="1">
                        <div class="bk-moreBtn">
                            <button id="morebtn" class="btn btn-outline" type="button" style="display: none;"><i class="fa fa-angle-down fa-fw"></i><?php echo $GLOBALS['MSG']['MORE'];?></button>
                        </div>
                    </div>
                </div>
                <!-- 点击买入卖出 -->
                <div class="sellBuyAlert" v-if="sellBuyAlert" v-cloak>
                    <p class="fInput">
                        <!-- 请输入金额 -->
                        <input placeholder="<?php echo $GLOBALS['MSG']['TRD_NUM'];?>!" @blur="buyMinFun" oninput = "value=value.replace(/[^\d||\.]/g,'')"  v-model="trdnum" />
                        <!-- 请输入100的整数倍 -->
                        <span class="err" v-if="trdNumStatus==1"><?php echo $GLOBALS['MSG']['N100'];?></span>
                        <!-- 交易金额不能小于 -->
                        <span class="err" v-if="trdNumStatus==2"><?php echo $GLOBALS['MSG']['LT_NUM'];?>{{parseInt(this.trdmin)}}</span>
                        <!-- 交易金额不能高于 -->
                        <span class="err" v-if="trdNumStatus==3"><?php echo $GLOBALS['MSG']['GT_NUM'];?>{{parseInt(this.trdMax)}}</span>
                    </p>
                    <p>
                            <!-- 请输入交易密码 -->
                         <input type="password" placeholder="<?php echo $GLOBALS['MSG']['REAL_PASSWORD'];?>!" v-model="trpwd"/>
                    </p>
                    <button class="btn btn-success" @click="submitBuySell"><?php echo $GLOBALS['MSG']['OK'];?></button> 
                    <button class="btn btn-info" @click="buySell"><?php echo $GLOBALS['MSG']['NO'];?></button> 
                </div>
                <div class="mask" v-if="mask" v-cloak></div>
                <div class="buyingquantity" v-if="buyingquantity" v-cloak>
                    <p class="input_num">
                        <?php echo $GLOBALS['MSG']['BUY_CNYX_COUNT'];?>
                    </p>
                    <button id="btn" @click="Determines"><?php echo $GLOBALS['MSG']['SURE'];?></button>
                </div>
                <div class="sellwindow" v-if="sellwindow" v-cloak>
                    <p class="input_num" v-if="outMinStatus==1"><?php echo $GLOBALS['MSG']['SELL_CNYX_COUNT'];?></p>
                    <!-- 请输入最小賣出CNYX数量！ -->
                    <p class="input_num" v-if="outMinStatus==2"><?php echo $GLOBALS['MSG']['MINBUY_CNYX'];?></p>
                    <!-- 賣出CNYX数量必须是100的整数倍 -->
                    <p class="input_num" v-if="outMinStatus==3"><?php echo $GLOBALS['MSG']['BUY100NCNYX'];?></p>
                    <!-- 最小賣出CNYX数量必须是100的整数倍 -->
                    <p class="input_num" v-if="outMinStatus==4"><?php echo $GLOBALS['MSG']['MINBUY100_CNYX'];?></p>
                    <p class="input_num" v-if="outMinStatus==5"><?php echo $GLOBALS['MSG']['BUY_MINCNYX'];?>：{{sellout}}</p>
                    <button id="btn" @click="Determine"><?php echo $GLOBALS['MSG']['SURE'];?></button>
                </div>
                <div class="popup" v-if="popup" v-cloak>
                    <p class="input_num" v-text="updisplay"></p>
                    <button id="btn" @click="Determineplay"><?php echo $GLOBALS['MSG']['SURE'];?></button>
                </div>
                <div flex="main:center cross:center" class="set_trade_pwd" v-if="transactionpwd" v-cloak>
                    <div class="pwd_form_contain white100_bg relative_dom">
                        <div class="close_btn close_icon" @click="closeicon"></div>
                        <p class="pwd_title gray600_f">
                            <?php echo $GLOBALS['MSG']['TRACT_PSW'];?>
                        </p>
                        <div class="trade_pwd_form ">
                            <div class="input_g relative_dom">
                                <input autocomplete="off" class="texts" onpaste="return false" oncontextmenu="return false" oncopy="return false" oncut="return false" type="password" maxlength="25" placeholder="<?php echo $GLOBALS['MSG']['TRACT_PSW'];?>" v-model="trpwd">
                            </div>
                            <div class="submit_tab">
                                <button type="button" class="default_btn orange500_bg white100_f" @click="Determineplaypwd" :style="{cursor:(!dubclick?'wait':'pointer')}"><?php echo $GLOBALS['MSG']['SURE'];?></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div flex="main:center cross:center" class="set_trade_pwd" v-if="Selltransaction" v-cloak>
                <div class="pwd_form_contain white100_bg relative_dom">
                    <div class="close_btn close_icon" @click="closeicon"></div>
                    <p class="pwd_title gray600_f">
                        <?php echo $GLOBALS['MSG']['TRACT_PSW'];?>
                    </p>
                    <div class="trade_pwd_form">
                        <div class="input_g relative_dom">
                            <input autocomplete="off" class="texts" onpaste="return false" oncontextmenu="return false" oncopy="return false" oncut="return false" type="password" maxlength="25" placeholder="<?php echo $GLOBALS['MSG']['TRACT_PSW'];?>" v-model="sellpwd">
                        </div>
                        <div class="submit_tab">
                            <button type="button" class="default_btn orange500_bg white100_f" @click.stop.prevent="Selltransac" :style="{cursor:(!dubclick?'wait':'pointer')}"><?php echo $GLOBALS['MSG']['SURE'];?></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div flex="main:center cross:center" class="set_trade_pwd" v-if="recharge" v-cloak>
            <div class="pwd_form_contain white100_bg relative_dom">
                <div class="close_btn close_icon" @click="closeicon"></div>

                <div class="trade_pwd_form">
                    <div class="input_g numwer">
                        <p style="display: inline-block;position: relative;top: 15px;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                            <?php echo $GLOBALS['MSG']['AMOUNT'];?>：</p>
                        <input autocomplete="off" type="text" v-model="numwer" style="width:73%" @focus="focus()">
                        <p v-text="msgg" style="margin-left: 76px;color:red"></p>
                    </div>

                    <div class="input_g relative_dom">
                        <p style="display: inline-block;position: relative;top: 14px;margin-top: 20px;">
                            <?php echo $GLOBALS['MSG']['F_TRACT_PSW'];?>：</p>
                        <input autocomplete="off" class="texts" onpaste="return false" oncontextmenu="return false" oncopy="return false" oncut="return false" type="password" maxlength="25" placeholder="<?php echo $GLOBALS['MSG']['TRACT_PSW'];?>" v-model="sellpwds" style="width:73%"
                            @focus="focus()">
                        <p v-text="msgs" style="margin-left: 76px;color:red"></p>
                    </div>
                    <div class="submit_tab">
                        <button type="button" class="default_btn orange500_bg white100_f" :style="{cursor:(!dubclick?'wait':'pointer')}" @click.stop.prevent="Recharge"><?php echo $GLOBALS['MSG']['SURE'];?></button>
                    </div>
                    <div flex="dir:right" v-show="forgetPwd" style="display:none">
                        <a class="blue500_f link" href="/user?set=tradepwd">
                            <?php echo $GLOBALS['MSG']['FORGET_PWD'];?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div flex="main:center cross:center" class="set_trade_pwd" v-if="drawal" v-cloak>
            <div class="pwd_form_contain white100_bg relative_dom">
                <div class="close_btn close_icon" @click="closeicon"></div>

                <div class="trade_pwd_form">
                    <div class="input_g numwer">
                        <p style="display: inline-block;position: relative;top: 15px;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                            <?php echo $GLOBALS['MSG']['AMOUNT'];?>：</p>
                        <input autocomplete="off" type="text" v-model="numdrawal" style="width:73%" @focus="focus()">
                        <p v-text="msgg" style="margin-left: 76px;color:red"></p>
                    </div>

                    <div class="input_g relative_dom">
                        <p style="display: inline-block;position: relative;top: 14px;margin-top: 20px;">
                            <?php echo $GLOBALS['MSG']['F_TRACT_PSW'];?>：</p>
                        <input autocomplete="off" class="texts" onpaste="return false" oncontextmenu="return false" oncopy="return false" oncut="return false" type="password" maxlength="25" placeholder="<?php echo $GLOBALS['MSG']['TRACT_PSW'];?>" v-model="pwdrawal" style="width:73%"
                            @focus="focus()">
                        <p v-text="msgs" style="margin-left: 76px;color:red"></p>
                    </div>
                    <div class="submit_tab">
                        <button type="button" class="default_btn orange500_bg white100_f" @click.stop.prevent="withdrawal" :style="{cursor:(!dubclick?'wait':'pointer')}"><?php echo $GLOBALS['MSG']['SURE'];?></button>
                    </div>
                    <div flex="dir:right" v-show="forgetPwd" style="display:none">
                        <a class="blue500_f link" href="/user?set=tradepwd">
                            <?php echo $GLOBALS['MSG']['FORGET_PWD'];?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- 密码输入错误等等所有弹窗里面的提示语 -->
        <div class="Backgroundpop" v-if="Backgroundpop" v-cloak>
            <p class="back_tips" v-text="bckpop"></p>
        </div>
        <!-- 确认收款按钮提示语 -->
        <div class="isshow" v-show="isshow" v-cloak>
            <p style="text-align: center;color:green;font-size:16px" v-text="condow"></p>
        </div>

        <!-- 支付弹窗 -->
        <div class="Paymentmethod" v-if="paydetails" v-cloak>
            <h4>
                <?php echo $GLOBALS['MSG']['LOOK_FOR_ORDER_DETAIL'];?>
            </h4>
            <div class="Paymentmethod2" style="padding:15px 20px;text-align:center;display: inline-block">
                <div style="display:inline-block;vertical-align:middle;text-align:left;">
                    <p style="font-size:16px; margin-top:5px">
                        <b v-if="lookData.type==1"><?php echo $GLOBALS['MSG']['BUYER_PHONENUM'];?></b>
                        <b v-else><?php echo $GLOBALS['MSG']['SELLER_PHONENUM'];?></b>：
                        <span v-text="lookData.moble"></span>
                    </p>
                    <p style="font-size:16px; margin-top:5px">
                        <b v-if="lookData.type==1"><?php echo $GLOBALS['MSG']['BUYER_NAME'];?></b>
                        <b v-else><?php echo $GLOBALS['MSG']['SELLER_NAME'];?></b>：
                        <span v-text="lookData.truename"></span>
                    </p>

                    <p style="font-size:16px; margin-top:5px">
                        <b v-if="lookData.paytype==2"><?php echo $GLOBALS['MSG']['WECHAT_ACCOUNT'];?></b>
                        <b v-else-if="lookData.paytype==1"><?php echo $GLOBALS['MSG']['ONLINE_BANK_ACCOUNT'];?>:</b>
                        <b v-else-if="lookData.paytype==3"><?php echo $GLOBALS['MSG']['ALIPAY_ACCOUNT'];?></b>
                        <span v-text="lookData.bankcard"></span>
                    </p>
                    <p style="font-size:16px; margin-top:5px">
                        <b><?php echo $GLOBALS['MSG']['TRAND_WAY'];?>：</b>
                        <span v-if="lookData.paytype==2"><?php echo $GLOBALS['MSG']['WECHAT'];?></span>
                        <span v-else-if="lookData.paytype==1"><?php echo $GLOBALS['MSG']['ONLINE_BANK'];?></span>
                        <span v-else-if="lookData.paytype==3"><?php echo $GLOBALS['MSG']['ALIPAY'];?></span>
                    </p>
                    <p style="font-size:16px; margin-top:5px">
                        <b><?php echo $GLOBALS['MSG']['TRAND_AMOUNT'];?>：</b><span v-text="lookData.num"></span>
                    </p>
                    <p style="font-size:16px; margin-top:5px">
                        <b><?php echo $GLOBALS['MSG']['ORDER_NUMBER'];?>：</b><span v-text="lookData.tradeno"></span>
                    </p>
                    <p style="font-size:16px; margin-top:5px">
                        <b><?php echo $GLOBALS['MSG']['STATUS'];?>：</b><span v-text="lookData.status"></span>
                    </p>

                </div>
                <p style="height:65%;display:inline-block;vertical-align:middle;max-width:30%;margin-left:50px;">
                    <img v-if="lookData.paytype!=1" :src="lookData.img" style="width:100%;max-width:100%;" />
                    <p>
            </div>
            <div class="Paymentmethod3" style="padding:15px 10px 15px 10px;">
                <p style="color: red;">
                    <?php echo $GLOBALS['MSG']['WARM_PROMPT'];?>;</p>
                <p style="color: red;">1.
                    <?php echo $GLOBALS['MSG']['REMITTANCE'];?>;</p>
                <p style="color: red;">2.
                    <?php echo $GLOBALS['MSG']['SUSPEND_FROM_TRAND'];?>;</p>
                <p>3.
                    <?php echo $GLOBALS['MSG']['ACCOUNT_NO'];?>;</p>
                <p>4.
                    <?php echo $GLOBALS['MSG']['REALNAME_AUTHENTICATION'];?>;</p>
                <p>5.
                    <?php echo $GLOBALS['MSG']['NEGOTIATION_PROCESS_CONNECT'];?>;</p>
            </div>
            <div class="clones" @click="clones">&times;</div>
        </div>

    </div>
</div>
<div class="history">
</div>
</div>
</div>
<script>
    document.querySelector("li.transaction ").className += " now_nav"
</script>

<?php  include PATH_TPL.'/tpl.noCopyRightFooter.phtml';?>
