<?php  include PATH_TPL.'/tpl.header.phtml';?>

<div id="indexs" class="index_warp">
  <u class="hide_dom" v-once ref="login"><?php if (isset($_SESSION['user'])) { echo 1; } else { echo 2 ;} ?></u>
  <!--  @click="getCoin"  -->
  <div class="ggao_top_new">
      <!-- <h1 class="bannerTitle"><?php echo $lang['BANNER_TITLE']; ?></h1> -->
    <div class="swiper-container" flex="cross:center" id="bannerContainer"> 
      <div class="swiper-wrapper">
        
        <a class="swiper-slide white100_f" href="/user/candy">
         <img src="/imgs/banner-011.jpg"/>
        </a>
        <a class="swiper-slide white100_f" href="/user/candy">
          <img src="/imgs/banner-00.jpg"/>
        </a>
        <a class="swiper-slide white100_f" href="/user/candy">
          <img src="/imgs/banner00.jpg"/>
        </a>
        
      </div>
	  <div class="swiper-pagination swiper_page"></div>
      
    </div>
    <!--banner  -->
    <div id="particles" class="ggao_back"></div>
    <!-- news -->
    <!-- <div class="swiper_message" flex="main:center">
      <div class="swiper_message_inner" flex="cross:center dir:left box:justify">
        <div class="white100_f"><?php echo $lang['INDEX_TRADE_DOBI_ANNOUNCE'] ?> <i class="message_voice"></i></div>
        <ul class="message_list" flex="dir:left box:mean">
          <?php for ($i = 0; $i < count($data['news']); $i++){ ?>
            <li>
              <a href="/news/detail/<?php echo $data['news'][$i]['id'] ?>.html" flex="cross:center">
                <span class="news_content"><?php echo $data['news'][$i]['title']; ?></span>
                <span>【<?php echo $data['news'][$i]['time']; ?>】</span>
              </a>
            </li>
          <?php } ?>
        </ul>
        <a class="message_more" href="/news/category/4" class="message_more"><?php echo $lang['MORE'] ?></a>
      </div>
    </div> -->
  </div>
<!-- market -->
  <div class="warp_bottom" flex="main:center cross:center dir:top">
    <!-- <div class="ggao_table_bottom white100_bg" :style="{height: calculates + 'px'}"></div> -->
    <div class="ggao_table_height white100_bg">
      <div class="ggao_ul" ref="tab_header" flex="box:last">
        <ul flex="dir:left" v-cloak>
            <!-- <li :class="['table_change', {table_active_change: indexs == 1}]" @click="tabChange(1, 'choose')" flex="dir:left cross:center main:center">
              <span :class="['table_self', {table_self_have: indexs == 1}]"></span><?php echo $lang['INDEX_TRADE_SELF'];?>
            </li>
            <li :class="['table_change', {table_active_change:indexs == index+2 }]"
                v-for="(item, index) in coinNum" v-cloak @click="tabChange(index+2, item)">{{item.toUpperCase() == 'NEW' ? '<?php echo $lang['NEW_AREA'] ?>': item.toUpperCase()}}
            </li> -->
            <li :class="['table_change', {table_active_change: indexs==1}]" @click="tabChange(1, 'choose')" flex="dir:left cross:center main:center">
              <span :class="['table_self', {table_self_have: indexs==1}]"></span><?php echo $lang['INDEX_TRADE_SELF'];?>
            </li>
            <li :class="['table_change', {table_active_change:indexs == 2}]"
                v-for="(item, index) in coinNum" v-cloak @click="tabChange(2, item)">
                  {{item.toUpperCase() == 'NEW' ? '<?php echo $lang['NEW_AREA'] ?>': item.toUpperCase()}}
            </li>
        </ul>
        <?php //find btn ?>
        <div class="search_btn" flex="cross:center dir:left">
          <input type="text" name="" placeholder="<?php echo $lang['SEARCH_TRADE_COUPLE']; ?>"
            v-model="searchInpt"
            :class="['search_input', 'gray350_bg', {search_foucs: search, search_btn_after: !search}]"
            @blur="searchBtn()"
            @focus="search = true"
            @keyup="searchData" v-cloak maxlength="6">
        </div>
      </div>
      <div class="ggao_tab">
        <div class="table_div" v-cloak>
          <div class="ggao_tab_th" flex="box:mean">
            <span flex="cross:center" @click='order("coin")' class="ggao_trs_first" flex-box="0">
              <span :class="['ggao_tab_order', {ggao_order_click: !orderFn, ggao_order_down: orderFn}]" v-if="orderType === 'coin'"></span>
              <?php echo $lang['INDEX_TRADE_DUI'];?>
            </span>
            <span flex="cross:center" class="ggao_tabs_new" @click='order("price")'>
              <span :class="['ggao_tab_order', {ggao_order_click: !orderFn, ggao_order_down: orderFn}]" v-if="orderType === 'price'"></span>
              <?php echo $lang['INDEX_TRADE_NEW']; ?>
            </span>
            <span flex="cross:center dir:right"  @click='order("ratio")' flex-box="0" class="ggao_trs_first_ratio">
              <span :class="['ggao_tab_order', {ggao_order_click: !orderFn, ggao_order_down: orderFn}]" v-if="orderType === 'ratio'"></span>
              <?php echo $lang['INDEX_TRADE_CHANGE']; ?>
            </span>
            <span flex="cross:center dir:right" @click='order("max")'><?php echo $lang['INDEX_TRADE_HIGHT']; ?>
              <span :class="['ggao_tab_order', {ggao_order_click: !orderFn, ggao_order_down: orderFn}]" v-if="orderType === 'max'"></span>
            </span>
            <span flex="cross:center dir:right" @click='order("min")'>
              <span :class="['ggao_tab_order', {ggao_order_click: !orderFn, ggao_order_down: orderFn}]" v-if="orderType === 'min'"></span>
              <?php echo $lang['INDEX_TRADE_LOW']; ?>
            </span>
            <span flex="cross:center dir:right" @click='order("money")' class="ggao_tabs_right">
              <span :class="['ggao_tab_order', {ggao_order_click: !orderFn && !first, ggao_order_down: orderFn && !first}]" v-if="orderType === 'money'"></span>
              <?php echo $lang['INDEX_TRADE_VOLUME']; ?>
            </span>
          </div>
          <div class="ggao_tr" v-for="(item, index) in coinListNum" v-if="coinListNum.length > 0">
            <a :href="'/trade/'+ item.coin" flex="box:mean cross:center" flex-box="1">
              <span flex="cross:center dir: left" class="relative_dom ggao_trs ggao_trs_first"  flex="dir:left" flex-box="0">
                <span flex-box="0"
                @click.stop.prevent="clickMySelf(item.coin, index)"
                :class="['tab_choose',item.selected?'tab_choose_no':'tab_choose_click']">
                </span>
                <img :src="item.coinurl?item.coinurl:'/coin/coin.png'" alt="" class="coin_img" v-cloak>
                <span flex-box="1" flex="dir:left cross:center" class="ggao_trs_first_span">
                  <span class="yellow500_f">{{item.coin.split('_')[0].toUpperCase()}}</span>
                  <!-- ({{item.display}})/  -->
                  <!-- <span class="gray400_f">{{item.coin.split('_')[1].toUpperCase()}}</span> -->
                </span>
              </span>
              <span flex="cross:center dir:left" class="ggao_trs ggao_tabs_new">{{item.price ? spliceEight(item.price) : item.price}} 
                <!-- / &nbsp;<span class="gray400_f">${{item.usd ? item.usd.slice(0, 8) : item.usd}}</span> -->
              </span>
              <span flex="cross:center dir:right" class="ggao_trs ggao_trs_first_ratio" flex-box="0" :class="{red400_f: item.ratio < 0, green400_f: item.ratio > 0}">{{item.ratio > 0 ?'+' + item.ratio +'%': item.ratio +'%'}}</span>
              <!-- / &nbsp;<span class="gray400_f">{{'￥' + moneyCal(item.currency, item.price, item.max)}} -->
              <span flex="cross:center dir:right" class="ggao_trs">{{item.max ? spliceEight(item.max) : item.max}} </span></span>
               <!-- / &nbsp;<span class="gray400_f">{{'￥' + moneyCal(item.currency, item.price, item.min)}} -->
              <span flex="cross:center dir:right" class="ggao_trs">{{item.min ? spliceEight(item.min) : item.min}}</span></span>
              <span flex="cross:center dir:right" class="ggao_trs ggao_tabs_right">{{item.money ? spliceEight(item.money) : item.money}}</span>
            </a>
          </div>
          <div v-if="coinListNum.length <= 0" v-cloak :class="{ggao_tab_no_data: !loading, ggao_tab_loading: loading}" flex="cross:center main:center">
              <p class="ggao_tab_p gray400_f" v-if="!loading && indexs == 1 && !searching"><?php echo $lang['INDEX_TRADE_DOBI_NO_COIN']; ?></p>
              <p class="ggao_tab_p gray400_f" v-if="!loading && (indexs != 1 || searching)"><?php echo $lang['INDEX_TRADE_DOBI_NO_DATA']; ?></p>
          </div>
        </div>
      </div>
      <!-- scrolltop -->
      <!-- <a class="jump_top" @click="gotoTop"></a> -->
    </div>
  <!-- aboutus -->
    <div class="warp_abuout_us" flex="cross:center dir:top">
      <h3><?php echo $GLOBALS['MSG']['SERVICE_PROVIDER'];?></h3>   
      <p><?php echo $GLOBALS['MSG']['MANAGE_SERVICE'];?></p>
      <ul class="about_us_exp" flex="main:justify">
        <li flex="cross:center dir:top">
          <div class="about_exp_img about_exp_flex"></div>
          <p><?php echo $lang['INDEX_FAST']; ?></p>
          <div class="about_exp_p">
            <p><?php echo $GLOBALS['MSG']['QUOTATION_SERVICE'];?></p>
            <p><?php echo $GLOBALS['MSG']['PROJECT_DYAMIC'];?></p>
            <p><?php echo $GLOBALS['MSG']['MARKET_TREND'];?></p>
            <!-- <p><?php echo $lang['INDEX_FAST_FOUR']; ?></p>
            <p><?php echo $lang['INDEX_FAST_FIVE']; ?></p> -->
          </div>
        </li>
        <li flex="cross:center dir:top">
          <div class="about_exp_img about_exp_fast"></div>
          <p><?php echo $lang['INDEX_FLEX']; ?></p>
          <div class="about_exp_p">
            <p><?php echo $GLOBALS['MSG']['DIFFERENT_COUNTRY'];?></p>
            <p><?php echo $GLOBALS['MSG']['COMPANY_COPERATION'];?></p>
            <p><?php echo $GLOBALS['MSG']['VIRTUAL_CURRENCY'];?></p>
          </div>
        </li>
        <li flex="cross:center dir:top">
          <div class="about_exp_img about_exp_safe"></div>
          <p><?php echo $lang['INDEX_SAFE']; ?></p>
          <div class="about_exp_p">
            <p><?php echo $GLOBALS['MSG']['WIND_CONTROL'];?></p>
            <p><?php echo $GLOBALS['MSG']['SAFE_SYSTEM'];?></p>
            <p><?php echo $GLOBALS['MSG']['CAN_TECH'];?></p>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <!-- footlinks -->
  <div class="index_link">
    <div class="logo">
      <img src="/svg/lendenexLogo.svg" />
    </div>
    <div class="index_link_inner" flex="main:justify">
      <div flex-box="1" flex="dir:right cross:stretch" class="index_link_right">
        <!-- <ul class="link_ul link_padd" flex-box="1">
          <li class="link_title white100_f">更多</li>
          <?php // block.cc ?>
          <li class="link_li">
            <a href="https://mifengcha.com/" class="white100_f">钱包下载</a>
          </li>
          <li class="link_li">
            <a href="https://mifengcha.com/" class="white100_f" >各币区块浏览器</a>
          </li>
          <li class="link_li">
            <a href="https://mifengcha.com/" class="white100_f" >费用说明</a>
          </li>
        </ul>  -->
        <ul class="link_ul link_padd" flex-box="1">
          <li class="link_title white100_f"><?php echo $lang['INDEX_TRADE_DOBI_FREES_TITLE']; ?></li>
          <li class="link_li white100_f">
            <a href="https://www.huocoin.wang/index/policy" class="white100_f"><?php echo $lang['INDEX_TRADE_DOBI_TERMS']; ?></a>
          </li>
          <li class="link_li">
            <a href="/news/detail/346.html" class="white100_f" ><?php echo $GLOBALS['MSG']['FARE_CHAIM'];?></a>
          </li>
          <!-- <li class="link_li">
            <a href="https://www.huocoin.com/news/detail/<?php if (LANG == 'en') { echo '514.html';} else {echo '512.html';} ?>" class="white100_f"><?php echo $lang['INDEX_TRADE_DOBI_FREES']; ?></a>
          </li> -->
        </ul>
        <?php // 工具 ?>
        <ul class="link_ul link_padd" flex-box="1">
          <li class="link_title white100_f"><?php echo $lang['INDEX_TRADE_DOBI_TOOL']; ?></li>
          <!-- <li class="link_li"><a href="https://api.huocoin.com/" class="white100_f"><?php echo $lang['INDEX_TRADE_DOBI_API']; ?></a></li> -->
          <li class="link_li">
            <a href="/news/detail/334.html" class="white100_f"><?php echo $GLOBALS['MSG']['PURSE_DOWNLOAD'];?></a>
          </li>
          <!-- <li class="link_li">
            <a href="https://mifengcha.com/" class="white100_f" >费用说明</a>
          </li> -->
          <li class="link_li">
            <a href="/news/detail/338.html" class="white100_f" ><?php echo $GLOBALS['MSG']['COIN_BLOCKCHAIN_BROWSE'];?></a>
          </li>
        </ul>
        <!-- // about  -->
        <ul class="link_ul link_padd" flex-box="1">
          <li class="link_title white100_f"><?php echo $lang['INDEX_TRADE_DOBI_ABOUTS']; ?></li>
          <li class="link_li">
            <!-- <a href="https://www.huocoin.com/news/detail/<?php if (LANG == 'en') { echo '519.html';} else {echo '511.html';} ?>" class="white100_f"><?php echo $lang['INDEX_TRADE_DOBI_ABOUT']; ?></a> -->
            <a href="news/detail/315.html"><?php echo $lang['INDEX_TRADE_DOBI_ABOUT']; ?></a>
          </li>
       
          <li class="link_li"><a href="/news/category/4" class="white100_f"><?php echo $lang['INDEX_TRADE_DOBI_ANNOUNCE']; ?></a></li>
          <li class="link_li">
            <a href="/news/detail/<?php if (LANG == 'en') { echo '526.html';} else {echo '525.html';} ?>" class="white100_f"><?php echo $lang['INDEX_TRADE_DOBI_APPLE']; ?></a>
          </li>
        </ul>
        <ul class="link_ul link_padd" flex-box="1">
          <li class="link_title white100_f"><?php echo $GLOBALS['MSG']['QUICK_OPERATE'];?></li>
          <li class="link_li">
            <a href="/user/realinfo" class="white100_f"><?php echo $GLOBALS['MSG']['NAME_AUTHENTICATION'];?></a>
          </li>
          <li class="link_li">
            <a href="/trade" class="white100_f"><?php echo $GLOBALS['MSG']['COIN_TRANSFER'];?></a>
          </li>
          <li class="link_li">
            <a  href="/user/coinin" class="white100_f"><?php echo $layout['lang']['USER_NAV_COIN_IN'] ?></a> 
            <a href="/user/coinout" class="white100_f"><?php echo $layout['lang']['USER_NAV_COIN_OUT'] ?></a>
          </li>
          <li class="link_li">
            <a href="/user/recharge" class="white100_f"><?php echo $GLOBALS['MSG']['RECHARGE'];?></a>
          </li>
        </ul>

          <!--<li class="link_li white100_f"><?php echo $lang['INDEX_TRADE_DOBI_TOKEN']; ?>：huocoin</li>-->
          <!--<li class="link_li white100_f"><?php echo $lang['INDEX_TRADE_DOBI_MEDIA_EMAIL']; ?>：media@huocoin.com</li>-->

        <!-- <ul class="link_ul contact_us" flex-box="2">
          <li class="link_title white100_f"><?php echo $lang['INDEX_TRADE_DOBI_CONTACT']; ?></li>
          <li class="link_li white100_f"><?php echo $GLOBALS['MSG']['KF_EMAIL'];?>：hwCSD@huocoin.wang</li>
          <li class="link_li white100_f"><?php echo $GLOBALS['MSG']['SOCIATE_EMAIL'];?>：Hw-community@huocoin.wang</li>
          <li class="link_li white100_f"><?php echo $lang['INDEX_TRADE_DOBI_BUSINESS']; ?>: business@huocoin.wang</li>
          <li class="link_li white100_f"><?php echo $lang['INDEX_INTER_BUSINESS']; ?>：application@huocoin.wang</li>

          <li class="link_li white100_f"><?php echo $lang['TELL_WE']; ?>：00852-67493962 &nbsp;&nbsp;&nbsp;00852-65292365‬</li>
          <li class="link_li white100_f"><?php echo $lang['WEB_QQ']; ?>：681023842 &nbsp;&nbsp;&nbsp;952095800</li>
        </ul> -->
	  </div>
	  <div flex-box="0" class="index_link_left">
        <p class="index_link_logo white100_f" flex="cross:center">
		  <img src="/svg/huocoinLogo.svg" alt="">
        </p>
        <!-- <ul class="index_link_img" flex="dir:left box:mean">
          <li class="link_qq" @mouseout.stop="erOut('qq')" @mouseover="erIn('qq')">
            <transition mode="out-in" name="fadeOut" v-cloak>
              <div class="link_er" v-if="showEr.qq">
                 <p class="link_er_p"><?php echo $lang['WEB_QQ']; ?></p>
                 <p class="link_er_p">535997102</p>
                <p class="link_er_p">681023842</p>
              </div>
            </transition>
          </li>
          <li class="link_wechat" @mouseout.stop="erOut('wechat')" @mouseover="erIn('wechat')">
            <transition mode="out-in" name="fadeOut" v-cloak>
              <div class="link_er" v-if="showEr.wechat">
                <p class="link_er_p"><?php echo $lang['WECHART_THREE']; ?></p>
                <img src="/imgs/WECHART5.png" alt="<?php echo $lang['WECHART_ONE']; ?>">
              </div>
            </transition>
          </li>
          <li class="link_tele" @mouseout.stop="erOut('tele')" @mouseover="erIn('tele')">
            <transition mode="out-in" name="fadeOut" v-cloak>
              <div class="link_er" v-if="showEr.tele"  style="left:25%">
                <p class="link_er_p"><?php echo $lang['WECHART_FOUR']; ?></p>
                <img src="/imgs/Telegraph.png" alt="<?php echo $lang['WECHART_FOUR']; ?>">
              </div>
            </transition>
          </li>
        </ul>  -->
      </div>
    </div>
  </div>
  <my-alert v-cloak v-on:callback="callfn" :show-status.sync="nowStatus">
    <div class="alert_contents black900_f" slot="content">{{errMesAlert}}</div>
    <span slot="btnTitle" class="black900_f"><?php echo $layout['lang']['DETERMINE'] ?></span>
  </my-alert>
 <!--  show($activity) -->
<?php if($mcc_act_status){ ?>
  <div class="active_win" v-cloak>
    <img class="act_img" @click.stop="getRedPacket" src="/imgs/side_red_packetn.<?php echo $la; ?>.png" />
    <transition mode="out-in" name="fadeOut">
      <div class="mask_full" v-if="activeMsg"></div>
    </transition>
    <transition mode="out-in" name="zoom">
      <div class="act_mob" v-if="activeMsg" @click.stop="activeMsg = !activeMsg">
        <div flex="main:center cross:center dir:top">
          <div class="act_con_box white100_bg orange500_f relative_dom" :class="{'plus2_act_<?php echo $la; ?>': actType=='plus2'}">
            <p class="white100_f no_sel" v-if="actType === 'mcc'">{{activeMsg}}</p>
            <div class="sub_tips white100_f no_sel" v-if="actType === 'mcc'"><?php echo $lang['PLEASE_CHECK_DETAIL']; ?></div>
            <div class='act_sure_btn' v-if="actType === 'mcc'"><a href="/user/candy?tab=3"><?php echo $lang['VIEW_NOW']; ?></a></div>
            <div class='act_sure_btn' v-if="actType === 'plus2'"><a href="/news/detail/273.html">立即查看</a></div>
          </div>
        </div>
      </div>
    </transition>
  </div>
  <?php } ?>
  <!-- annoucealert nologin(_SESSION not user_data)localtion not address  -->
 <?php if(!$_SERVER["QUERY_STRING"]){?>
    <div class="mask_contain" id="winBg" flex="main:center cross:center"   v-if="winHtml.header&&!sessionStorage.win"
    onClick="document.querySelector('#indexs').removeChild(document.getElementById('winBg'));sessionStorage.win='openBrowser';
      " v-cloak>
      <div class="winBox relative_dom" flex="dir:top main:left">
        <div class="winHeader" flex="main:justify dir:justify box:justify cross:center">
          <h3 v-text="winHtml.header"></h3>
          <span class="closeBtn" onClick="document.querySelector('#indexs').removeChild(document.getElementById('winBg'));sessionStorage.win='openBrowser';
            ">&times;</span>
        </div>
        <gemini-scrollbar
          class=" winBody " >
          <div v-html="winHtml.body.replace(/&nbsp;/ig,'')" class="inner_annouce my-scroll-bar"></div>
        </gemini-scrollbar>
      </div>
    </div>
  <?php } ?>
</div>
<!-- cdn -->
<script>document.querySelector("li.index").className+=" now_nav"</script>
<script src='/until/particles.min.js'></script>
<?php  include PATH_TPL.'/tpl.index.footer.phtml';?>

