<div class="rf_main gray50_bg" id="bank" flex="dir:top" style="min-width: 890px">
	<div class="nav-crumbs hide_767" flex-box="0">
		<?php echo $lang["USER_NAV_TITLE"] ?> &gt; <a class="active-tab">
		<?php echo $GLOBALS['MSG']['C2C_METHED_OF_COLLECT'];?></a>
	</div>
	<div v-if="<?php echo empty($auto)?false:"$auto != 2"?>" class="mainBox" v-cloak>
		<h3><?php echo $GLOBALS['MSG']['UN_REALNAME_AUTHENTICATION'];?>！<a href="/user/realinfo" class="minBtn bg_reds" style="float:right;color:#2d6cfa"><?php echo $GLOBALS['MSG']['REALNAME_AUTHENTICATION'];?>>></a></h3>
	</div>
	<div v-else  v-cloak>
		<div class="mplan_tabs" >
			<ul class="mplan_change_tab" flex="dir:left">
			    <li @click="tabChange(1)" :class="[{mplan_active_li: postData.index == 1}]"  v-text=`<?php echo $GLOBALS['MSG']['BANKCARD_MANAGE'];?>`></li>
				<li @click="tabChange(2)" :class="[{mplan_active_li: postData.index == 2}]"  v-text=`<?php echo $GLOBALS['MSG']['WECHAT_MANAGE'];?>`></li>
				<li @click="tabChange(3)" :class="[{mplan_active_li: postData.index == 3}]"  v-text=`<?php echo $GLOBALS['MSG']['ALIPAY_MANAGE'];?>`></li>
			</ul>
		</div>
		<div class="mainBox white100_bg">
		<!-- 银行卡管理 -->
			<div v-show="postData.index == 1" v-cloak class="bankList">
				<button class="btnAdd" @click="alertFun('bankShow')"><?php echo $GLOBALS['MSG']['ADD_BANKCARD'];?></button>
				<div v-for="(itime,key) in bankList">
					<h4><span v-text="itime.name"></span><span style="float:right" v-text="itime.username"><?php echo $GLOBALS['MSG']['PF_BANK'];?></span></h4>
					<p style="margin:10px 0px" v-text="itime.bankcard"></p>
					<div class="operat">
						<button class="minBtn bg_red" @click="openBind(itime.id,key,'delbank')"><?php echo $GLOBALS['MSG']['UNTYING'];?></button>
						<span style="float:right">
							<button class="off"  @click="openBind(itime.id,key,'mysave')"
								:style="parseInt(itime.status)?'background:#0075a9':'background:#666'">
								<i :style="parseInt(itime.status)?'left:30px':'left:0.4px'"></i>
							</button>
							<a v-show="parseInt(itime.status)"><?php echo $GLOBALS['MSG']['OPEN_USE'];?></a>
							<a v-show="!parseInt(itime.status)"><?php echo $GLOBALS['MSG']['CLOSE_USE'];?></a>
						</span>
					</div>
				</div>
			</div>
			<!-- // 微信管理 -->
			<div v-if="postData.index == 2" v-cloak>
				<p style="margin-bottom:20px">
					<b><?php echo $GLOBALS['MSG']['WECHAT_BIND'];?>：</b>
					<button class="off" userid="8340" status="2"  @click="openBind(postData.id,'','mysave')"
						:style="parseInt(postData.status) ? 'background:#0075a9':'background:#666'">
						<i :style="parseInt(postData.status) ?'left:30px':'left:0.4px'"></i>
					</button>
					<span v-show="parseInt(postData.status)"><?php echo $GLOBALS['MSG']['OPEN_USE'];?></span>
					<span v-show="!parseInt(postData.status)"><?php echo $GLOBALS['MSG']['CLOSE_USE'];?></span>
				</p>
				<p style="margin-bottom:20px"  v-cloak>
					<b><?php echo $GLOBALS['MSG']['NAME'];?>:</b><span v-text="realName"></span>
				</p>
				<p style="margin-bottom:20px">
					<b><?php echo $GLOBALS['MSG']['WECHAT_ACCOUNT'];?>:</b>
					<input v-model="postData.bankcard"
						@blur="verify('wx','postData','bankcard','<?php echo $GLOBALS['MSG']['RIGHT_WECHAT_ACCOUNT'];?>！')"    
						placeholder="<?php echo $GLOBALS['MSG']['RIGHT_WECHAT_ACCOUNT'];?>！"  type="text"/>
					<b class="red" v-show="errStatus.bankcard" v-text="errStatus.bankcard"></b>
				</p>
				<h3 style="margin-bottom:6px"> <?php echo $GLOBALS['MSG']['UPLOAD_QRCODE'];?>:<a class="red">( <?php echo $GLOBALS['MSG']['UN_MORE'];?> )</a></h3>
				<p class="p_bg" style="margin-bottom:20px">
					<a class="red"><?php echo $GLOBALS['MSG']['WECHAT_QRCODE_GAIN'];?>：<?php echo $GLOBALS['MSG']['OPEN_WECHAT'];?> -&gt; <?php echo $GLOBALS['MSG']['CLICK_ACCEPT'];?> -&gt; <?php echo $GLOBALS['MSG']['CLICK_SAVE_PHONE'];?> -&gt; <?php echo $GLOBALS['MSG']['AFTER_UPLOAD'];?></a></p>
				<p style="margin-bottom:20px">
					<b><?php echo $GLOBALS['MSG']['WECHAT_QRCODE'];?>:</b>
					<span class="addImg">
						<!-- 显示 -->
						<img :src="postData.img" alt="<?php echo $GLOBALS['MSG']['WECHAT_QRCODE'];?>"/>
						<input type="file" @change='uploadFile' accept="image/*"  value="" class="filepath"/>
						<button class="minBtn bg_red" v-show="!postData.status"><?php echo $GLOBALS['MSG']['UPLOAD_CODE'];?></button>
						<button class="minBtn bg_red" v-show="postData.status"><?php echo $GLOBALS['MSG']['CLICK_MODIFY'];?></button>
						<!-- 提示 -->
						<b  v-show="postData.status" :class="errStatus.imgErr=='√' ? 'green650_bg' :'bg_red'" v-text="errStatus.imgErr"></b>
					</span>
				</p>
				<div v-if="reset">
					<p style="position:relative;margin-bottom:20px" v-cloak>
						<b><?php echo $GLOBALS['MSG']['PHONE_VERI'];?>:</b>
						<span>
							<input v-model="postData.moblePhone"
								@blur="verify('moble','postData','moblePhone','<?php echo $GLOBALS['MSG']['ENTER_RIGHT_YZM'];?>！')" 
								placeholder="<?php echo $GLOBALS['MSG']['ENTER_RIGHT_YZM'];?>！"  type="text"/>
							<b class="red" v-show="errStatus.moblePhone" v-text="errStatus.moblePhone"></b>
							<button class="bg_red" v-show="numT>0"><b v-text="numT"></b><?php echo $GLOBALS['MSG']['AFTER_SECOND_GAIN'];?></button>
							<button class="bg_red" v-show="numT<0" @click="getmoble()"><?php echo $GLOBALS['MSG']['GAIN'];?></button>
						</span>
					</p>
					<p>
						<input type="button" class="bg_red sure_btn" value="<?php echo $GLOBALS['MSG']['MODIFY_BIND'];?>" @click="submit()" style="text-cengin">
					</p>
				</div>
			</div>
			<!-- 支付宝管理 -->
			<div v-show="postData.index == 3" v-cloak>
				<p style="margin-bottom:20px" v-cloak>
					<span><?php echo $GLOBALS['MSG']['ALIPAY_BIND'];?>：</span>
					<button class="off" userid="8340" status="2"  @click="openBind(postData.id,'','mysave')"
						:style="parseInt(postData.status) ? 'background:#0075a9':'background:#666'">
						<i :style="parseInt(postData.status) ?'left:30px':'left:0.4px'"></i>
					</button>
					<span v-show="parseInt(postData.status)"><?php echo $GLOBALS['MSG']['OPEN_USE'];?></span>
					<span v-show="!parseInt(postData.status)"><?php echo $GLOBALS['MSG']['CLOSE_USE'];?></span>
				</p>
				<p style="margin-bottom:20px"  v-cloak>
					<b><?php echo $GLOBALS['MSG']['NAME'];?>:</b><span v-text="realName"></span>
				</p>
				<p style="margin-bottom:20px">
					<span><?php echo $GLOBALS['MSG']['ALIPAY_ACCOUNT'];?>:</span>
					<input v-model="postData.bankcard"
						@blur="verify('zfb','postData','bankcard','<?php echo $GLOBALS['MSG']['ENTER_RIGHT_ALIPAY_ACCOUNT'];?>！')" 
						placeholder="<?php echo $GLOBALS['MSG']['CLOSENTER_RIGHT_ALIPAY_ACCOUNTE_USE'];?>！"  type="text"/>
					<b class="red" v-show="errStatus.bankcard" v-text="errStatus.bankcard"></b>
				</p>
				<h3 style="margin-bottom:6px"><?php echo $GLOBALS['MSG']['UPLOAD_ALIPAY_CODE'];?> :<a class="red">( <?php echo $GLOBALS['MSG']['UN_MORE'];?> )</a></h3>
				<p class="p_bg" style="margin-bottom:20px">
					<a class="red"><?php echo $GLOBALS['MSG']['ALIPAY_CODE_GAIN'];?>：<?php echo $GLOBALS['MSG']['OPEN_ALIPAY'];?> -&gt; <?php echo $GLOBALS['MSG']['CLICK_ACCEPT'];?> -&gt; <?php echo $GLOBALS['MSG']['CLICK_SAVE_PHONE'];?> -&gt; <?php echo $GLOBALS['MSG']['AFTER_UPLOAD'];?></a></p>
				<p style="margin-bottom:20px" >
					<b><?php echo $GLOBALS['MSG']['ALIPAY_ACCEPT_CODE'];?>:</b>
					<span class="addImg">
						<!-- 显示 -->
						<img :src="postData.img" alt="<?php echo $GLOBALS['MSG']['ALIPAY_ACCEPT_CODE'];?>"/>
						<input type="file" @change='uploadFile' accept="image/*"  value="" class="filepath"/>
						<button class="minBtn bg_red" v-show="!postData.status"><?php echo $GLOBALS['MSG']['UPLOAD_CODE'];?></button>
						<button class="minBtn bg_red" v-show="postData.status"><?php echo $GLOBALS['MSG']['CLICK_MODIFY'];?></button>
						<!-- 提示 -->
						<b  v-show="postData.status" :class="errStatus.imgErr=='√' ? 'green650_bg' :'bg_red'" v-text="errStatus.imgErr"></b>
					</span>
				</p>
				<div v-if="reset">
					<p style="position:relative;margin-bottom:20px;">
						<b><?php echo $GLOBALS['MSG']['PHONE_YZM'];?>:</b>
						<span>
							<input v-model="postData.moblePhone"
								@blur="verify('moble','postData','moblePhone','<?php echo $GLOBALS['MSG']['ENTER_RIGHT_YZM'];?>！')" 
								placeholder="<?php echo $GLOBALS['MSG']['ENTER_RIGHT_YZM'];?>"  type="text"/>
							<b class="red" v-show="errStatus.moblePhone" v-text="errStatus.moblePhone"></b>
							<button class="bg_red" v-show="numT>0"><b v-text="numT"></b><?php echo $GLOBALS['MSG']['AFTER_SECOND_GAIN'];?></button>
							<button class="bg_red" v-show="numT<0" @click="getmoble()"><?php echo $GLOBALS['MSG']['GAIN'];?></button>
						</span>
					</p>
					<p>
						<input type="button" class="bg_red sure_btn" value="<?php echo $GLOBALS['MSG']['MODIFY_BIND'];?>" @click="submit()" style="text-cengin"/>
					</p>
				</div>
			</div>
		</div>
		<!-- tan  kuang 1-->
		<div class="alertBox" v-cloak v-if="bankShow">
			<div class="Bankwindow">
				<div class="headers">
					<span style="font-size:16px"><?php echo $GLOBALS['MSG']['ADD_BANKCARD'];?></span>
					<button class="close" @click="alertFun('bankShow')">&times</button>
				</div>
				<div>
					<div class="login_text" style="margin-top:14px">
						<div class="alert_wrap_title"><?php echo $GLOBALS['MSG']['NOTE_NAME'];?>：</div>
						<span>
							<input v-model="BankData.name"
								@blur="verify('regStr','BankData','name','<?php echo $GLOBALS['MSG']['ENTER_RIGHT_NAME'];?>')" 
							placeholder="<?php echo $GLOBALS['MSG']['ENTER_NOTE'];?>"  type="text"/>
							<b class="red" v-show="errStatus.name" v-text="errStatus.name"></b>
						</span>
					</div>
					<!-- <div class="login_text">
						<div class="alert_wrap_title">開戶省市：</div>
						<span class="controls">
							<select class="prov texts" v-model="BankData.bankProv" name="prov">
								<option value="-1">--请选择--</option>
								<option value="0">北京</option>
								<option value="1">天津</option>
								<option value="2">河北</option>
								<option value="3">山西</option>
								<option value="4">内蒙古</option>
								<option value="5">辽宁</option>
								<option value="6">吉林</option>
								<option value="7">黑龙江</option>
								<option value="8">上海</option>
								<option value="9">江苏</option>
								<option value="10">浙江</option>
								<option value="11">安徽</option>
								<option value="12">福建</option>
								<option value="13">江西</option>
								<option value="14">山东</option>
								<option value="15">河南</option>
								<option value="16">湖北</option>
								<option value="17">湖南</option>
								<option value="18">广东</option>
								<option value="19">广西</option>
								<option value="20">海南</option>
								<option value="21">重庆</option>
								<option value="22">四川</option>
								<option value="23">贵州</option>
								<option value="24">云南</option>
								<option value="25">西藏</option>
								<option value="26">陕西</option>
								<option value="27">甘肃</option>
								<option value="28">青海</option>
								<option value="29">宁夏</option>
								<option value="30">新疆</option>
								<option value="31">香港</option>
								<option value="32">澳门</option>
								<option value="33">台湾</option>
								<option value="34">国外</option>
							</select>
							<select class="city texts" v-model="BankData.bankCity" name="city">
							</select>
						</span>
					</div> -->
					<div class="login_text">
						<div class="alert_wrap_title"><?php echo $GLOBALS['MSG']['KHZH'];?>：</div>
						<span>
							<input v-model="BankData.username" 
								@blur="verify('regStr','BankData','username','<?php echo $GLOBALS['MSG']['ENTER_RIGHT_KHZH'];?>')" 
								type="text" placeholder="<?php echo $GLOBALS['MSG']['ENTER_KHZH'];?>" autocomplete="off"/>
							<b class="red" v-show="errStatus.username" v-text="errStatus.username"></b>
						</span>
					</div>
					<div class="login_text">
						<div class="alert_wrap_title"><?php echo $GLOBALS['MSG']['KH_NAME'];?>：</div>
						<input v-model="realName"  type="text" placeholder="<?php echo $GLOBALS['MSG']['UN_BIND_YHK'];?>！" disabled="true"/>
					</div>
					<div class="login_text">
						<div class="alert_wrap_title"><?php echo $GLOBALS['MSG']['YHK_NUM'];?>：</div>
						<span>
							<input type="text" v-model="BankData.bankcard" 
								@blur="verify('bank','BankData','bankcard','<?php echo $GLOBALS['MSG']['ENTER_RIGHT_YHK_NUM'];?>')" 
								placeholder="<?php echo $GLOBALS['MSG']['ENTER_Y_YHK_NUM'];?>!" />
							<b class="red" v-show="errStatus.bankcard" v-text="errStatus.bankcard">1111</b>
						</span>
					</div>
					<div class="login_text">
						<div class="alert_wrap_title"><?php echo $GLOBALS['MSG']['LETTER_VERIFICATION'];?>：</div>
						<span>
							<input type="text" 
								@blur="verify('moble','BankData','moblePhone','<?php echo $GLOBALS['MSG']['ENTER_LETTER_CODE'];?>')" 
								v-model="BankData.moblePhone"  placeholder="<?php echo $GLOBALS['MSG']['ENTER_LETTER_CODE'];?>!"/>
							<b class="red" v-show="errStatus.moblePhone" v-text="errStatus.moblePhone">1111</b>
							<button class="bg_red" v-show="numT>0"><b v-text="numT"></b><?php echo $GLOBALS['MSG']['AFTER_SECOND_GAIN'];?></button>
							<button class="bg_red" v-show="numT<0" @click="getmoble()"><?php echo $GLOBALS['MSG']['GAIN'];?></span>
						</span>
					</div>
					<div class="login_button">
						<input type="button"  value="<?php echo $GLOBALS['MSG']['ADD_RIGHT_NOW'];?>" @click="submit()"/>
					</div>
				</div>
			</div>
			<div></div>
		</div>	
		<!-- tan  kuang 2-->
		<div class="alertBox" v-if="alertMsg"  v-cloak>
			<div class="Bankwindow">
				<div class="headers red">
					<span style="font-size:16px" v-text="alertMsg"></span>
					<button class="close" @click="alertFun('close')">&times</button>
				</div>
			</div>
		</div>
	</div>
</div>