<div class="user_index_dom gray200_bg" id="candy" flex-box="1" style="min-width: 900px">
  <div class="user_index">
    <ul class="user_pan candy_hide" flex="main:left">
      <li> <?php echo $lang['USER_NAV_MY_ASSETS'] ?><span class="user_gt">&gt;</span></li>
      <li class="blue200_f"><?php echo $GLOBALS['MSG']['INVITE_SHARE'];?></li>
    </ul>
    <div class="candy_choose"  v-cloak>
      <transition model="out-in" name="candy">
        <ul class="candy_tabs" v-cloak v-if="tabChnage">
          <li @click="coinClick(1)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 1 }]"><?php echo $GLOBALS['MSG']['INVITE_SHARE'];?></li>
        </ul>
      </transition>
    </div>
  <!-- 邀请分红 -->
	<div v-show="tab == 1 " v-cloak>
		<table width=100% >
        <thead class="user_tabs" rules='none'>
            <tr class="user_tabs_tr user_tabs_th white100_bg">
              <th><?php echo $GLOBALS['MSG']['RECOMMENT_FRIEND'];?></th>
              <th ><?php echo $GLOBALS['MSG']['REGISTER_TIME'];?></th>
              <th><?php echo $GLOBALS['MSG']['FRIEND_REALNAME_STATUS'];?></th>
              <th ><?php echo $GLOBALS['MSG']['TRADING_SHARE_BONUS'];?></th>
              <th ><?php echo $GLOBALS['MSG']['PLATFORM_TOP_UP_BONUS'];?></th>
              <th ><?php echo $GLOBALS['MSG']['C2C_PREPAID_DIVIDEND'];?></th>
              <th ><?php echo $GLOBALS['MSG']['TOTAL_DIVIDEND'];?></th>
              <th><?php echo $GLOBALS['MSG']['OPERATE'];?></th>
            </tr>
        </thead>
        <tbody class="user_tabs" rules='none'>
          <tr v-cloak  v-show="!tabLoging && !no_data"   v-for="(item, key) in list"   :class="['user_tabs_tr', 'gray600_f', 'user_tabs_td',key%2!= 0?'white100_bg':'gray200_bg']">
            <td v-text="item.mo"></td> 
            <td v-text="item.created"></td>
            <td>
            <!-- <span v-if="item.status==0">未提交</span>
            <span v-else-if="item.status==1">未实名</span> -->
            <span v-if="item.status==2"><?php echo $GLOBALS['MSG']['HAD_REAL_NAME'];?></span>
            <span v-else><?php echo $GLOBALS['MSG']['UN_REAL_NAME'];?></span>
            <!-- <span v-else-if="item.status==3">已拒绝</span> -->
            </td> 
            <td class="fee" v-text="item.tradeFee?item.tradeFee:0"></td>
            <td class="fee" v-text="item.platfromFee?item.platfromFee:0"></td>
            <td class="fee" v-text="item.c2cFee?item.c2cFee:0"></td>
            <td class="fees" v-text="item.totalFee"></td>

            <td><a v-if="item.totalFee" class="minBtn activeBg" :href="'bonusdetails?id='+item.uid"><?php echo $GLOBALS['MSG']['DETAIL'];?></a></td>
          </tr>
        </tbody>
        <div class="user_tabs_span white100_bg" v-show="tabLoging || no_data" v-cloak flex="dir:top cross:center main:center">
          <span :class="{loding: tabLoging, no_data: no_data}"></span>
          <u class="no_data_font" v-if="no_data"><?php echo $lang['NO_RECORD_NOW']; ?></u>
        </div>
		</table>
  </div>
  <div class="tabsPages" :class="all > 1 ? 'page-list-contain':''">
      <pages :all = "all" v-on:get-tabs="getcoindata"
        :page-name="'<?php echo $GLOBALS['MSG']['PAGE'];?>'"
        :jump-to-title="'<?php echo $GLOBALS['MSG']['JUMP'];?>'"
        :home-title="'<?php echo $GLOBALS['MSG']['NUMBER_HOME'];?>'"
        :last-title="'<?php echo $GLOBALS['MSG']['NUMBER_FOOR'];?>'"
        :currentpage ="currentpage"
        @keydown="" v-if="all && all != 1">
      </pages>
  </div>
  </div>
</div>
