<div class="user_index_dom gray200_bg" id="candy" flex-box="1" style="min-width: 900px">
  <div class="user_index">
    <ul class="user_pan candy_hide" flex="main:left">
      <li><?php echo $lang['USER_NAV_MY_ASSETS'] ?><span class="user_gt">&gt;</span></li>
      <li><a class="blue200_f" href="/user/bonusinvite"><?php echo $GLOBALS['MSG']['INVITE_SHARE'];?></a> &gt; </li>
      <li><?php echo $GLOBALS['MSG']['SHARE_DETAIL'];?></li>
    </ul>
    <div class="candy_choose"  v-cloak>
      <transition model="out-in" name="candy">
        <ul class="candy_tabs" v-cloak>
          <li @click="coinClick(1)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 1 }]"><?php echo $GLOBALS['MSG']['TRADING_SHARE_BONUS'];?></li>
          <li @click="coinClick(2)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 2 }]"><?php echo $GLOBALS['MSG']['PLATFORM_TOP_UP'];?></li>
          <li @click="coinClick(3)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 3 }]"><?php echo $GLOBALS['MSG']['C2C_PREPAID'];?></li>
        </ul>
      </transition>
    </div>
    <!-- 交易分红 -->
		<table width=100% v-show="tab==1">
        <thead class="user_tabs" rules='none'>
            <tr class="user_tabs_tr user_tabs_th white100_bg">
              <th><?php echo $GLOBALS['MSG']['TRANSAC_KIND'];?></th>
              <th><?php echo $GLOBALS['MSG']['TRANSAC_TIME'];?></th>
              <th><?php echo $GLOBALS['MSG']['TRANSAC_PRICE'];?></th>
              <th><?php echo $GLOBALS['MSG']['TRANSATION_COUNT'];?></th>
              <th><?php echo $GLOBALS['MSG']['BUY_IN'];?>/<?php echo $GLOBALS['MSG']['SELL'];?></th>
              <th><?php echo $GLOBALS['MSG']['GAIN_BONUS'];?></th>
            </tr>
        </thead>
        <tbody class="user_tabs" rules='none'>
          <tr v-cloak  v-show="!tabLoging && !no_data"   v-for="(item, key) in list"   :class="['user_tabs_tr', 'gray600_f', 'user_tabs_td',key%2!= 0?'white100_bg':'gray200_bg']">
            <td v-text="item.coin_from"></td> 
            <td v-text="item.created"></td>
            <td v-text="parseFloat(item.price)"></td> 
            <td v-text="parseFloat(item.number)"></td>
            <td v-text="item.opt==2?'卖出':'买入'"></td>
            <td class="fee" v-text="parseFloat(item.fee)"></td>
          </tr>
        </tbody>
		</table>
    <!-- 平台充值  C2C充值 -->
    <table width=100% v-show="tab!=1" v-cloak>
        <thead class="user_tabs" rules='none'>
            <tr class="user_tabs_tr user_tabs_th white100_bg">
              <th ><?php echo $GLOBALS['MSG']['RECHARGE_TIME'];?></th>
              <th><?php echo $GLOBALS['MSG']['TOP_UP_AMOUNT'];?></th>
              <th ><?php echo $GLOBALS['MSG']['GAIN_BONUS'];?></th>
            </tr>
        </thead>
        <tbody class="user_tabs" rules='none'>
          <tr  v-show="!tabLoging && !no_data"   v-for="(item, key) in list"   :class="['user_tabs_tr', 'gray600_f', 'user_tabs_td',key%2!= 0?'white100_bg':'gray200_bg']">
            <td v-text="item.created"></td>
            <td v-text="parseFloat(item.number)"></td>
            <td class="fee" v-text="parseFloat(item.fee)"></td>
          </tr>
        </tbody>
		</table>
    <div class="user_tabs_span white100_bg" v-show="tabLoging || no_data" v-cloak flex="dir:top cross:center main:center">
        <span :class="{loding: tabLoging, no_data: no_data}"></span>
        <u class="no_data_font" v-if="no_data"><?php echo $lang['NO_RECORD_NOW']; ?></u>
      </div>
    <div class="tabsPages" :class="all > 1 ? 'page-list-contain':''">
      <pages :all = "all" v-on:get-tabs="getcoindata"
        :page-name="'<?php echo $GLOBALS['MSG']['PAGE'];?>'"
        :jump-to-title="'<?php echo $GLOBALS['MSG']['JUMP'];?>'"
        :home-title="'<?php echo $GLOBALS['MSG']['NUMBER_HOME'];?>'"
        :last-title="'<?php echo $GLOBALS['MSG']['NUMBER_FOOR'];?>'"
        :currentpage ="currentpage"
        @keydown="" v-if="all && all != 1">
      </pages>
    </div>
  </div>
</div>

