<div class="user_index_dom gray200_bg" id="candy" flex-box="1" style="min-width: 900px">
  <div class="user_index">
    <ul class="user_pan candy_hide" flex="main:left">
      <li> <?php echo $lang['USER_NAV_MY_ASSETS'] ?><span class="user_gt">&gt;</span></li>
      <li class="blue200_f"><?php echo $lang['CANDY_GET'] ?></li>
    </ul>
    <div class="candy_choose" v-show="!coinDetail" v-cloak>
      <transition model="out-in" name="candy">
        <ul class="candy_tabs" v-cloak v-if="tabChnage">
          <li @click="coinClick(1)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 1 }]">
            <?php echo $lang['CANDY_TYPE_BTC']?></li>
          <!--活动领取列表 -->
          <li @click="coinClick(2)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 2 }]">
            <?php echo $lang['CANDY_TYPE_WCG']?></li>
          <!--点赞活动 -->
          <li @click="coinClick(3)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 3 }]">
            <?php echo $lang['CANDY_TYPE_HD']?></li>
        </ul>
      </transition>
    </div>
    <!-- 持幣分紅 -->
    <div v-show="tab == 1 && !coinDetail" v-cloak>
      <!-- jsj公用表格頭部 slot="thead" -->
      <table width=100%>
        <thead class="user_tabs" rules='none'>
          <tr class="user_tabs_tr user_tabs_th white100_bg">
            <th><?php echo $lang['CANDY_BZ']?></th>
            <th class="candy_hide">
              <!-- <?php echo $lang['CANDY_QKGD']?> -->
              <?php echo $lang['CANDY_PDBL']?>
            </th>
            <th class="candy_hide"><?php echo $GLOBALS['MSG']['LEAST_HOLD'];?></th>
            <th><?php echo $GLOBALS['MSG']['BEGIN_TIME'];?></th>
            <th>
              <!-- <?php echo $lang['CANDY_YLQ']?> -->
              <?php echo $lang['CANDY_ZHITIME']?>
            </th>
            <th><?php echo $GLOBALS['MSG']['AVAILABLE_BALANCE'];?></th>
            <th><?php echo $GLOBALS['MSG']['HAD_RECEIVE'];?></th>
            <th><?php echo $lang['CANDY_CZ']?></th>
          </tr>
        </thead>
        <tbody class="user_tabs" rules='none'>
          <!-- 持幣分紅--循環的數據-->
          <tr v-cloak v-show="!tabLoging && !no_data"
            :class="['user_tabs_tr', 'gray600_f', 'user_tabs_td',key%2!= 0?'white100_bg':'gray200_bg']"
            @touchstart="coin_detail('start', item)" @touchmove="coin_detail('over')" @touchend="coin_detail('end')"
            v-for="(item, key) in dataList">
            <td v-text="item.name"></td>
            <td><?php echo $GLOBALS['MSG']['EVERYDAY'];?>{{item.rate}}</td>
            <!-- 最少持幣 -->
            <td v-text="item.min_number"></td>
            <td v-text="item.start_date"></td>
            <td v-text="item.end_date"></td>
            <td>
              <span>
                <!-- 可用余額 -->
                {{parseFloat(item.coin_over).toFixed(8)}}
                <!-- 可領取 -->
                <i v-if="item.number"><?php echo $lang['CANDY_CANGET']?>{{item.number}}</i>
              </span>
            </td>
            <td v-text="item.on_number">
            </td>
            <td>
              <button v-if="!item.number&&item.min_number<=item.coin_over" @click="gifts(item.name,key)"
                class="minBtn activeBg" :style="{cursor:(!moverClick?'wait':'pointer')}">
                <?php echo $lang['CANDY_CANGET']?>
              </button>
              <button v-else class="minBtn bg666"
                @click="gifts(item.name,key)"><?php echo $lang['CANDY_TH_GOT']?></button>
            </td>
          </tr>
        </tbody>
        <div class="user_tabs_span white100_bg" v-show="tabLoging || no_data" v-cloak
          flex="dir:top cross:center main:center">
          <span :class="{loding: tabLoging, no_data: no_data}"></span>
          <u class="no_data_font" v-if="no_data"><?php echo $lang['NO_RECORD_NOW']; ?></u>
        </div>
      </table>
    </div>
    <!-- //点赞活动-->
    <div v-if="tab == 3 && !coinDetail" v-cloak>
        <table class="user_tabs" rules='none'>
            <tr class="user_tabs_tr user_tabs_th white100_bg">
              <th><?php echo $lang['CANDY_BZ']?></th>
              <th class="candy_hide">数量</th>
              <!-- <?php echo $lang['CANDY_SHOWTIME']?> <?php echo $lang['CANDY_ZHITIME']?><?php echo $lang['CANDY_YLQ']?>-->
              <th>状态</th>
              <th>操作</th>
            </tr>
            <tr v-cloak v-show="!tabLoging && !no_data"
              :class="['user_tabs_tr', 'gray600_f', {white100_bg: index%2 != 0, gray200_bg: index%2 == 0}]"
              v-for="(item, index) in dataList" @touchstart="coin_detail('start', item)"
              @touchmove="coin_detail('over')" @touchend="coin_detail('end')">
              <td>{{item.coin}}</td>
              <td>{{parseFloat(item.price)}}</td>
              <td class="candy_hide" v-text="item.status==1?'未<?php echo $lang['CANDY_CANGET']?>':'<?php echo $GLOBALS['MSG']['HAD_RECEIVE'];?>'"></td>
              <td>
              <button type="button" :disabled="item.status==2"  @click="gifts('',index,item.id)"
                  :class="[{activeBg: item.status==1,minBtn: item.status==1, table_btn: item.button == 1}]">
                  {{item.status==1? "<?php echo $lang['CANDY_CANGET']?>" :"<?php echo $GLOBALS['MSG']['HAD_RECEIVE'];?>"}}
                </button>
              </td>
            </tr>
          </table>
    </div>
    <!--  //wcg活动奖励 -->
     <div v-if="tab == 2 && !coinDetail" v-cloak>
      
        <div>
          <table class="user_tabs" rules='none'>
            <tr class="user_tabs_tr user_tabs_th white100_bg">
              <th><?php echo $lang['CANDY_BZ']?></th>
              <th class="candy_hide">数量</th>
              <!-- <?php echo $lang['CANDY_SHOWTIME']?> <?php echo $lang['CANDY_ZHITIME']?><?php echo $lang['CANDY_YLQ']?>-->
              <th>状态</th>
              <th>操作</th>
            </tr>
            <tr v-cloak v-show="!tabLoging && !no_data"
              :class="['user_tabs_tr', 'gray600_f', {white100_bg: index%2 != 0, gray200_bg: index%2 == 0}]"
              v-for="(item, index) in dataList" @touchstart="coin_detail('start', item)"
              @touchmove="coin_detail('over')" @touchend="coin_detail('end')">
              <td>{{item.coin}}</td>
              <td>{{parseFloat(item.price)}}</td>
              <td class="candy_hide" v-text="item.status==1?'未<?php echo $lang['CANDY_CANGET']?>':'<?php echo $GLOBALS['MSG']['HAD_RECEIVE'];?>'"></td>
              <td>
                <button type="button" :disabled="item.status==2"  @click="gifts('',index,item.id)"
                  :class="[{activeBg: item.status==1,minBtn: item.status==1, table_btn: item.button == 1}]">
                  {{item.status==1? "<?php echo $lang['CANDY_CANGET']?>" :"<?php echo $GLOBALS['MSG']['HAD_RECEIVE'];?>"}}
                </button>
              </td>
            </tr>
          </table>
          <div class="user_tabs_span white100_bg" v-show="tabLoging || no_data" v-cloak
              flex="dir:top cross:center main:center">
              <span :class="{loding: tabLoging, no_data: no_data}"></span>
              <u class="no_data_font" v-if="no_data"><?php echo $lang['NO_RECORD_NOW']; ?></u>
            </div>
        </div>
    </div>
  </div>
  <my-alert v-cloak v-on:callback="callfn" :show-status.sync="nowStatus">
    <div class="alert_contents black900_f" slot="content">{{errMesAlert}}</div>
    <span slot="btnTitle" class="black900_f"><?php echo $lang['DETERMINE']; ?></span>
  </my-alert>
</div>