<!-- <link rel="stylesheet" href="/css/userCoinIn.css?v=<?php echo $clear_cache;?>"> -->
<div class="rf_main gray50_bg" flex="dir:top" id="coinin" style="min-width: 890px">
  <div class="nav-crumbs">
    <?php echo $lang["USER_NAV_MY_ASSETS"] ?> > <a class="active-tab" href="javascript: void(0);"><?php echo $lang['USER_NAV_COIN_IN'] ?></a>
  </div>
  <?php // 筛选条件 ?>
  <?php // include PATH_TPL.'/user/condition.phtml';?>
  <div class="condition_container white100_bg">
    <?php include PATH_TPL.'/user/condition/coin_list.phtml';?>
    <!-- <div class="coin_list_con"  flex="">
      <div class="gray600_f list_tit"  flex-box="0" ><?php echo $lang['CHANGE_TYPE'] ?>：</div>
      <div class="list_item" id="changeType" flex-box="1">
        <span class="gray500_f sel_coin" in-type="all"><?php echo $lang['CHANGE_ALL'] ?></span>
        <span in-type="1" class="gray500_f"><?php echo $lang['NORMAL_CHANGE'] ?></span>
        <span in-type="2" class="gray500_f"><?php echo $lang['TRADE_ORE'] ?></span>
        <span in-type="3" class="gray500_f"><?php echo $lang['COIN_GET'] ?></span>
      </div>
    </div> -->

    <!-- 000 -->
	<div  style="overflow: hidden;margin: 20px 0px;">
		<div class="coin_list_cons fl" >
			<div class="gray600_f list_tit" style="margin-left: 31px;font-weight:bold;" flex-box="0" >
        <span class="toggleEl coins" style="display:none"><?php echo $GLOBALS['MSG']['INTO_ZERO_FIVE'];?></span>
        <span class="toggle"  style="display:none">more </span>
        <span data-ntcoin="notecoin"></span>

        <?php echo $lang['USER_CDTION_WALLET_ADDR'] ?>：
      </div>
				<!-- 充币二维码 -->
				<div class="coin_in_qr gray500_f" flex="dir:left box:mean">
				<!-- // 錢包地址 ?> -->
				<div class="addr_lf">
					<div class="qr_code_img" id="qrcodeImg"><img src="/imgs/creating_qrCode.png"></div>
					<div class="addr_context" id="addrShow">
					<?php // 币地址，一定要放到  <span data-ccodetext> 标签内</span><?php echo $lang['USER_CDTION_WALLET_ADDR'] ?>
					<p class="code_addr_text"><span id="coinName"></p>
					<p class="wallt_addr">
            <span data-ccodetext='code' id="coinAddr" class="code_h" data-cTarget="true"></span>
            <span class="tipXrpNew"><?php echo $GLOBALS['MSG']['TIP_XRP_NEW'];?></span>
          </p>
					<?php // 复制钱包地址 ?>
					<p>
						<a class="copy_btn white100_f" href="javascript: void(0);" data-copy="ele" data-type="addr"><?php echo $GLOBALS['MSG']['USER_CDTION_COPY_WALLET_ADDR'];?></a>
						<!-- <a class="link-to-out" id="linkToOut" target="_blank" href="<?php echo Yaf_Registry::get("config")->yibi->url; ?>"><?php echo $lang['NOBTC_LINK']; ?></a> -->
					</p>
					</div>
					<?php // 地址生成中... ?>
					<div class="addr_loading" id="addrLoading" style="min-width: 110px;"><?php echo $lang['ADDR_LOADING'] ?></div>
					<?php // 無法充幣 提示 ?>
					<div class="can-not-in" id="canNotIn"><p><?php echo $lang['USER_CDTION_SO_SORRY'] ?><span data-ntcoin="notecoin"></span><?php echo $lang['USER_CDTION_CAN_NOT_COIN_IN']; ?></p></div>
				</div>
			<!-- -->
			</div>
			<div class="coin_list_con es_show"  flex="">
				<div class="gray600_f list_tit" style="margin-left: 31px;text-align: left;font-weight:bold;" flex-box="0"  >
          <span class="toggleEl" style="display:none"><?php echo $GLOBALS['MSG']['INTO_MORE_THAN_F'];?></span>
        <span data-ntcoin="notecoin" id="coins"></span>
        <!-- <?php echo $lang['USER_CDTION_WALLET_ADDR'] ?>： -->
        <span class="Label" style="display:none"><?php echo $GLOBALS['MSG']['LABEL'];?>：</span>
        <span class="addres" style="display:none"><?php echo $GLOBALS['MSG']['WALLET_ADDRESS'];?>:</span>
        
				 <!-- <?php echo $lang['COINOUT_LABEL']; ?>
					<span class="red500_f">(<?php echo $lang['COINOUT_IMPORTANT'] ?>)</span>： -->
				</div>
			</div>
		<!--  // eos 标签二维码 ?> -->
			<div class="coin_in_qr gray500_f es_show" flex="dir:left box:mean">
				<div class="addr_lf">
					<div class="qr_code_img" id="img_eos"><img src="/imgs/creating_qrCode.png"></div>
					<div class="all_code_mess" id="addrShowEos">
					<?php // 币标签，一定要放到  <span data-ccodetext-span> 标签内 ?>
					<p class="wallt_addr"><span data-ccodetext='code' id="eos_labels" class="code_h" data-cTarget="true"></span></p>
					<?php // 复制eos标签 ?>
					<p>
						<a class="copy_btn white100_f Label" href="javascript: void(0);" data-copy="ele" data-type="label"><?php echo $GLOBALS['MSG']['COINOUT_LABEL_COPY'];?></a>
						<a class="copy_btn white100_f addres" href="javascript: void(0);" data-copy="ele" data-type="label"><?php echo $GLOBALS['MSG']['USER_CDTION_COPY_WALLET_ADDR'];?></a>
					</p>
					</div>
					<div class="addr_loading" id="addrLoadingEos" style="min-width:111px"><?php echo $lang['ADDR_LOADING'] ?></div>
					<!-- <div class="can-not-in" id="canNotInEos"><p><?php echo $lang['USER_CDTION_SO_SORRY'] ?><span data-ntcoin="notecoin"></span><?php echo $lang['USER_CDTION_CAN_NOT_COIN_IN']; ?></p></div> -->
				</div>
			</div>
    </div>
    <!-- //表格 -->
		<div class="fromBox rgbClass fl" >
      <!-- <div class="pwd_form_contain white100_bg relative_dom">
      <h4 style="position: absolute;left: 127px;top: 20px;font-size: 15px;" >请输入您的转入地址</h4> 
      <div class="trade_pwd_form"> 
        <div class="input_g numwer">
            <p style="display: inline-block;position: relative;top: 15px;font-size: 12px;left: 5px;">钱包地址：</p>
            <input  autocomplete="off" type="text"   id="weike_dzbz"    class="texts addressa"  style="width:73%;margin-left: 10px;"> 
        </div> 
        <div class="input_g relative_dom">
            <p style="display: inline-block;position: relative;top: 14px;margin-top: 20px;font-size: 12px;left: 11px;">转入数量：</p>
            <input autocomplete="off" class="texts numbers" id="cny_num" onpaste="return false" oncontextmenu="return false" oncopy="return false" oncut="return false"  maxlength="25" oninput="this.value=this.value.replace(/[^\d||\.]/g,'')"  style="width:73%;margin-left: 10px;"> 
           
        </div> 
        <div class="submit_tab">
            <button class="coinin_up" >確定</button>
        </div> -->
			<div class="alert_address">
        <p class="title"><?php echo $GLOBALS['MSG']['ENTER_TRANSFER_ADDRESS'];?></p>
				<div class="wallet_address" >
          <div><?php echo $GLOBALS['MSG']['WALLET_ADDRESS'];?>：</div>
					<input type="text" class="texts addressa" id="weike_dzbz"  
          autocomplete="off" placeholder="请输入充币地址！"/>
				  <p class="adress" style="color:red"></p>
        </div>
				<div class="wallet_address">
          <div><?php echo $GLOBALS['MSG']['INTO_NUM'];?>：</div>
            <input type="text"  class="texts numbers" id="cny_num" 
            placeholder="请输入充币数量！"
            oninput="this.value=this.value.replace(/[^\d||\.]/g,'')" autocomplete="off" />
            <p class="nmbers" style="color:red"></p>
        </div>
				<button  id="coinin_up" ><?php echo $GLOBALS['MSG']['SURE'];?></button>
      </div>
        <!-- </div>
			</div> -->
    </div> 
		<!-- // 转入须知 -->
		<div class="coin_list_cons into_detail into_intro" data-pagename="<?php echo $pageName;?>">
			<h5><?php echo $lang['USER_CDTION_COIN_IN_INSTRUCTIONS']; ?></h5>
			<?php // 1. 此地址是您唯一且独自使用的转入地址，您可以同时进行多次转入 ?>
			<p><?php echo $lang['USER_CDTION_TIPS_ONE']; ?></p>
			<?php // 本地址  禁止充值除  之外的其他资产  ，任何其他资产充值将不可找回 ?>
      <p><?php echo $lang['USER_CDTION_TIPS_TWO_A']; ?><span class="red500_f"><?php echo $lang['USER_CDTION_TIPS_TWO_B']; ?><span data-ntcoin="notecoin"></span><?php echo $lang['USER_CDTION_TIPS_TWO_C']; ?></span><?php echo $lang['USER_CDTION_TIPS_TWO_D']; ?></p>
      <p class="rgbClass">3.&nbsp;<?php echo $GLOBALS['MSG']['CHECK_ENCRYTION'];?></p>
      <p class="red500_f">&nbsp;<?php echo $GLOBALS['MSG']['MIN_OK']; ?><span id="confirm" ></span> ,
        <?php echo $GLOBALS['MSG']['MIN_IN']; ?>:<span id="min_in" ></span></p>
		</div>
	</div>
    
  </div>
  <p class="user_tips gray500_f" id="userTips"></p>
  <?php include PATH_TPL.'/user/condition/time_condition.phtml'; ?>
  <?php // 表格 id="tBody" 不可删除 ?>
  <div class="out_table">
    <div class="coin-in-table shadow-cont">
      <div class="t-body" id="tBody">
        <table>
          <thead >
            <tr >
              <td><?php echo $lang['T_HEADER_ID'] ?></td>
              <td><?php echo $lang['TABLE_CHANGE'] ?></td>
              <td><?php echo $lang['T_HEADER_TIME'] ?></td>
              <td class="frequency"><?php echo $lang['T_HEADER_TXID'] ?> </td>
              <td class="displayhiding" style="display:none"><?php echo $GLOBALS['MSG']['WALLET_ADDRESS'];?></td>
              <td><?php echo $lang['T_HEADER_NUM'] ?></td>
              <td class="frequency"><?php echo $lang['T_HEADER_SURE_NUM'] ?></td>
              <td class="displayhiding" style="display:none"><?php echo $GLOBALS['MSG']['ORDER_NUMBER'];?></td>
              <td><?php echo $lang['T_HEADER_STATU'] ?></td>
              <td class="rgbClass"><?php echo $GLOBALS['MSG']['OPERATE'];?></td>
            </tr>
          </thead>
          <tbody id="dataBody" 
            status="<?php echo $GLOBALS['MSG']['PENDING_AUDIT'];?>" 
            undo="<?php echo $GLOBALS['MSG']['UNDO'];?>" 
            fail_undo="<?php echo $GLOBALS['MSG']['FAIL_UNDO'];?>" 
            withdrawn="<?php echo $GLOBALS['MSG']['WITHDRAWN'];?>" >
            <?php // 绿色文字 class添加"green-font" ; 红色文字 class 用 "red-font"?>
          </tbody>
          <?php //分頁 ?>
        </table>
        <?php // 没有数据时，显示该元素， 设置 display: block ?>
        <div class="no-data" id="tableNoData" style="display:block;">
          <div class="no-data-ctx">
            <span class="no-data-img"></span>
            <span><?php echo $lang['NO_RECORD_NOW']; ?></span>
          </div>
        </div>
      </div>
    </div>
    <div id="tabsPages" :class="all > 1 ? 'page-list-contain':''">
      <pages :all = "all" v-on:get-tabs="getTabs"
      :page-name="'<?php echo $lang['NUMBER_HOME_PA']?>'"
      :jump-to-title="'<?php echo $lang['NUMBER_TIAO_PA']?>'"
      :home-title="'<?php echo $lang['NUMBER_HOME']?>'"
      :last-title="'<?php echo $lang['NUMBER_FOOR']?>'"
      :currentpage ="currentpage"
      @keydown=""
      v-if="all && all != 1"></pages>
    </div>
  </div>
<div flex="main:center cross:center" class="set_trade_pwd" style="display:none">
 <div class="pwd_form_contain white100_bg relative_dom">
 <div class="close_btn close_icon"></div>
  <p class="pwd_title gray600_f"><?php echo $GLOBALS['MSG']['TRACT_PSW'];?></p> 
  <div class="trade_pwd_form">
  <div class="input_g relative_dom">
  <input autocomplete="off" class="texts paswadd" onpaste="return false" oncontextmenu="return false" oncopy="return false" oncut="return false" type="password" autocomplete="off" maxlength="25" placeholder="<?php echo $GLOBALS['MSG']['TRACT_PSW'];?>" ></div> 
  <p class="tips" style="color:red; margin-top:10px" ></p>
  <div class="submit_tab">
  <button  class="default_btn orange500_bg white100_f" id="Determine"><?php echo $GLOBALS['MSG']['SURE'];?></button>
  </div>
  <div flex="dir:right" class="forgetPwd" style="display:none"><a class="blue500_f link" href="/user?set=tradepwd" style="margin-top:5px"><?php echo $GLOBALS['MSG']['FORGET_PWD'];?></a></div>
  </div>
  </div>
  </div>
  </div>


</div>


 




