<div id="recharge">
    <p class="nav-crumbs">
        <?php echo $GLOBALS['MSG']['MY_ASSETS'];?> > <a class="active-tab"><?php echo $GLOBALS['MSG']['RECHARGE'];?></a>
    </p>
    <div class="header">
        <div class="headerBox">
            <div class="fromBox">
                <label class="recharge_title"> <?php echo $GLOBALS['MSG']['TOP_UP_AMOUNT'];?>：</label><input type="text" maxlength="12" v-model="num" placeholder=' <?php echo $GLOBALS['MSG']['ENTER_RECHARGE_ACCOUNT'];?>' oninput="this.value=this.value.replace(/[^\d]/g,'')"/><br>
                <label class="recharge_title"><?php echo $GLOBALS['MSG']['TOP_UP_TYPE'];?>：</label>
                  <?php foreach($method as $v){ ?>
                    <?php if($v['name']=='bank'){?>
                        <span :class="{'active':payType=='bank'}"> 
                            <img src="/imgs/bank.png" width="100">
                            <input type="radio" value="bank" name="payType"  v-model="payType" >
                        </span>
                    <?php }?>
                    <?php if($v['name']=='alipay'){?>
                        <span :class="{'active':payType=='alipay'}"> 
                            <img src="/imgs/alipay.png" width="100">
                            <input type="radio" value="alipay" name="payType"  v-model="payType" >
                        </span>
                    <?php }?>
                    <?php if($v['name']=='weixin'){?>
                        <span :class="{'active':payType=='weixin'}"> 
                            <img src="/imgs/weixin.png" width="100">
                            <input type="radio" value="weixin" name="payType"  v-model="payType" >
                        </span>
                    <?php }?>
                  <?php }?>
                
                <p style="padding-left:132px">
                    <button @click.stop.prevent="cnyin_up()" :style="{cursor:(!moreClick?'wait':'pointer')}" ><?php echo $GLOBALS['MSG']['PREPAID_IMMEDIATE'];?></button>
                </p>
            </div>
            <p class="tx_tips">
                <?php echo $GLOBALS['MSG']['SIMGLE_LIMIT'];?><b>100</b><?php echo $GLOBALS['MSG']['YUAN'];?>
                <?php echo $GLOBALS['MSG']['TO'];?><b>50000</b><?php echo $GLOBALS['MSG']['YUAN'];?>,<?php echo $GLOBALS['MSG']['ONLINE_PAY_LIMIT'];?><b>100</b><?php echo $GLOBALS['MSG']['YUAN'];?> <?php echo $GLOBALS['MSG']['TO'];?><b>500000</b><?php echo $GLOBALS['MSG']['YUAN'];?>,
                <?php echo $GLOBALS['MSG']['RECHARGE_ACCOUNT_EVERYDAY'];?><b>8:30</b>
                <?php echo $GLOBALS['MSG']['TO'];?><b>22:30</b>,
                <?php echo $GLOBALS['MSG']['WAIT_ACCOUNT'];?>。<br>
                <?php echo $GLOBALS['MSG']['WHEN_TEANSFER'];?>
                <b><?php echo $GLOBALS['MSG']['ORDER_NUMBER'];?></b><?php echo $GLOBALS['MSG']['MUST_NOTE'];?>,<?php echo $GLOBALS['MSG']['UN_ARRIVE'];?>
            </p>
        </div>
    </div>
    <h2 class="history" ><?php echo $GLOBALS['MSG']['RECORD'];?>
        <div  class="page"  v-cloak>
            <!-- <button @click="clickPage('f')" v-if="activePage!=1">首页</button>
            <button @click="clickPage('l')">上一頁</button>
            <span v-for="r in Math.ceil(pageSum/pageNum)-1">
                <button :class="[{active:activePage== i+( r - 1 )*pageNum}]"  :name="i"
                    v-if="activePage <= r*pageNum&&activePage>(r-1)*pageNum&&r<Math.ceil(pageSum/pageNum)" 
                    v-for="i in pageNum" 
                    v-text="i+( r - 1 )*pageNum">
                </button>
            </span>
            <button :class="[{active:activePage== i+parseInt(pageSum/pageNum)*pageNum}]"  name="000"

                v-if="activePage>parseInt(pageSum/pageNum)*pageNum"
                v-for="i in parseInt(pageSum % pageNum)" 
                v-show="i+parseInt(pageSum/pageNum)*pageNum"

                v-text="i+parseInt(pageSum/pageNum)*pageNum">
            </button>
            <span v-if="activePage<parseInt(pageSum/pageNum)*pageNum+1">
                <button>...</button>
                <button v-text="pageSum"></button>
            </span>
            <button @click="clickPage( 'r') ">下一頁</button>
            <button @click="clickPage( 'e')" v-if="activePage!=pageSum">尾页</button> -->
        </div>

    </h2>
    <table cellspacing="0" v-cloak>
        <thead>
            <tr>
                <th width="17%"><?php echo $GLOBALS['MSG']['RECHARGE_TIME'];?></th>
                <th><?php echo $GLOBALS['MSG']['ORDER_NUMBER'];?></th>
                <th  width="17%">
                    <span class="selectBox">
                        <p v-show="selectData=='all'"><?php echo $GLOBALS['MSG']['ALL_STATUS'];?></p>
                        <p v-show="selectData=='0'" ><?php echo $GLOBALS['MSG']['NO_PAY'];?></p>
                        <p v-show="selectData=='1'"><?php echo $GLOBALS['MSG']['RECHARGE_SUCCESS'];?></p>
                        <p v-show="selectData=='2'"><?php echo $GLOBALS['MSG']['PROCESS'];?></p>
                        <p v-show="selectData=='3'"><?php echo $GLOBALS['MSG']['WITHDRAWN'];?></p>
                        <div>   
                            <p @click="getTableList('all')"><?php echo $GLOBALS['MSG']['ALL_STATUS'];?></p>
                            <p @click="getTableList('0')"><?php echo $GLOBALS['MSG']['NO_PAY'];?></p>
                            <p @click="getTableList('1')"><?php echo $GLOBALS['MSG']['RECHARGE_SUCCESS'];?></p>
                            <p @click="getTableList('2')"><?php echo $GLOBALS['MSG']['PROCESS'];?></p>
                            <p @click="getTableList('3')"><?php echo $GLOBALS['MSG']['WITHDRAWN'];?></p>
                        </div>
                    </span>
                </th>
                <th><?php echo $GLOBALS['MSG']['TOP_UP_TYPE'];?></th>
                <th><?php echo $GLOBALS['MSG']['TOP_UP_AMOUNT'];?></th>
                <th><?php echo $GLOBALS['MSG']['ACTUAL_ACCOUNT'];?></th>
                <th><?php echo $GLOBALS['MSG']['INVITER_BONUS'];?></th>
                <th width="14%"><?php echo $GLOBALS['MSG']['OPERATE'];?></th>
            </tr>
        </thead>

        <tbody>
            <tr v-for="(itime,key) in tableList">
                <td v-text="itime.addtime"></td>
                <td v-text="itime.tradeno" style="color:#e60012"></td>
                <td >
                    <span v-show="parseInt(itime.status) == '0'"><?php echo $GLOBALS['MSG']['NO_PAY'];?></span>
                    <span v-show="parseInt(itime.status)=='1'"><?php echo $GLOBALS['MSG']['RECHARGE_SUCCESS'];?></span>
                    <span v-show="parseInt(itime.status)=='2'"><?php echo $GLOBALS['MSG']['PROCESS'];?></span>
                    <span v-show="parseInt(itime.status)=='3'"><?php echo $GLOBALS['MSG']['HAD_CANCEL'];?></span>
                </td>
                <td>
                    <span  v-if="itime.type=='alipay'"><?php echo $GLOBALS['MSG']['ALIPAY'];?></span>
                    <span  v-else-if="itime.type=='weixin'"><?php echo $GLOBALS['MSG']['WECHAT'];?></span>
                    <span  v-else-if="itime.type=='bank'"><?php echo $GLOBALS['MSG']['ONLINE_BANK'];?></span>
                </td>
                <td v-text="itime.num"></td>
                <td v-text="itime.mum"></td>
                <td v-text="itime.fee?parseFloat(itime.fee):'无'"></td>
                <td>
                    <span v-if="itime.status==0" class="operate_btn">
                        <button :style="{cursor:(!moreClick?'wait':'pointer')}" class="minBtn" @click.stop.prevent="undo(itime.id,key,'chexiao')"><?php echo $GLOBALS['MSG']['UNDO'];?></button>
                        <button :style="{cursor:(!moreClick?'wait':'pointer')}" class="minBtn" @click.stop.prevent="undo(itime.id,key,'Huikuan')"><?php echo $GLOBALS['MSG']['HAD_PAY'];?></button>
                    </span>
                    <button v-else-if="itime.status>0" :class="['minBtn',{'bg666':itime.status!=0}]" >
                        <span v-if="itime.status=='1'"><?php echo $GLOBALS['MSG']['RECHARGE_SUCCESS'];?></span>
                        <span v-else-if="itime.status=='2'"><?php echo $GLOBALS['MSG']['PROCESS'];?></span>
                        <span v-else-if="itime.status=='3'"><?php echo $GLOBALS['MSG']['HAD_CANCEL'];?></span>
                    </button>
                    <button class="minBtn" @click.stop.prevent="look(itime.id)"><?php echo $GLOBALS['MSG']['LOOK_FOR'];?></button>
                </td>
            </tr>
        </tbody>
    </table>
    <!--jsj 弹框 -->
    <div class="alertBox" v-if="ifshow" v-cloak>
        <div class="content">
            <header v-if="headerShow">
                <h3 v-text="headText"></h3>
                <button class="midBtn bgRed"  @click.stop.prevent="ifshowFun()">&times;</button>
            </header>
            <div class="body" v-if="bodyShow">
                <p>
                    <span v-if="lookData.type=='alipay'" class="red" ><?php echo $GLOBALS['MSG']['ALIPAY'];?></span>
                    <span v-else-if="lookData.type=='weixin'" class="red"><?php echo $GLOBALS['MSG']['WECHAT'];?></span>
                    <span v-else-if="lookData.type=='bank'" class="red"><?php echo $GLOBALS['MSG']['ONLINE_BANK'];?></span>
                <?php echo $GLOBALS['MSG']['TRANSFER_REMITTANCE'];?></p>
                <p ><?php echo $GLOBALS['MSG']['USE'];?>
                    <span v-if="lookData.type=='alipay'" class="red" ><?php echo $GLOBALS['MSG']['ALIPAY'];?></span>
                    <span v-else-if="lookData.type=='weixin'" class="red"><?php echo $GLOBALS['MSG']['WECHAT'];?></span>
                    <span v-else-if="lookData.type=='bank'" class="red"><?php echo $GLOBALS['MSG']['ONLINE_BANK'];?></span>
                    <?php echo $GLOBALS['MSG']['SCAN_QRCODE'];?>  
                    <button class="minBtn"><?php echo $GLOBALS['MSG']['CONNECT_SERVICE'];?></button>
                </p>
                    <div >
                    <div>
                        <p><b><?php echo $GLOBALS['MSG']['TRANSFER_ACCOUNT'];?>:</b> <span v-text="lookData.username"></span></p>
                        <p><b><?php echo $GLOBALS['MSG']['AGENT_NAME'];?>:</b> <span v-text="lookData.truename"></span></p>
                        <p><b><?php echo $GLOBALS['MSG']['ORDER_NO'];?>:</b> <span v-text="lookData.tradeno"></span></p>
                        <p><b><?php echo $GLOBALS['MSG']['OPEN_ACCOUNT_ADDRESS'];?>:</b> <span v-text="lookData.kaihu"></span></p>
                        <p><b><?php echo $GLOBALS['MSG']['PAY_AMMOUNT'];?>:</b> <span v-text="lookData.num"></span></p>
                        <p><b><?php echo $GLOBALS['MSG']['ARRIVE_VALUE'];?>:</b> <span v-text="lookData.mum"></span></p>
                        <p v-if="lookData.type=='bank'"><b><?php echo $GLOBALS['MSG']['OPEN_ACCOUNT_ADDRESS'];?>:</b> <span v-text="lookData.kaihu"></span></p>

                    </div> 
                    <div  v-if="lookData.type!='bank'"  class="img"><img :src="lookData.image" alt=""></div>
                </div>
            </div>
            <footer v-if="footShow">
                <p><?php echo $GLOBALS['MSG']['REMITTANCE_NOTE'];?>：<b class="red" v-text="lookData.tradeno"></b>.</p> 
                <p><?php echo $GLOBALS['MSG']['REMITTANCE_ARRIVE'];?>。</p>
            </footer>
        </div>
    </div>
</div>

    
